yggdrasil-network/yggdrasil-go

src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_other.go
This commit uses the `tun_linux.go` as a template to create `tun_darwin.go` which uses `ifconfig` instead of `ip` to set the interface IPv6 and MTU.
I also have written some code that uses syscalls, although for some reason I can't get this approach to work as expected. You may wish to pull https://github.com/neilalexander/yggdrasil-go/tree/macos-interface into a separate `macos-interface` branch in case anyone else has any bright ideas on how to fix it in the future!
=> Add tun_darwin.go

src/yggdrasil/ndp.go, src/yggdrasil/tun.go, src/yggdrasil/tun_other.go, src/yggdrasil/tun_windows.go
- Supports Windows using OpenVPN NDIS 6 TAP driver
- Supports NDP Neighbor Solicitation and Advertisements in `ndp.go`
- Supports TAP encapsulation and decapsulation in `tun.go`
=> Support for Windows, TAP interfaces and NDP

src/yggdrasil/debug.go, src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_linux.go, src/yggdrasil/tun_other.go, src/yggdrasil/tun_windows.go, yggdrasil.go
Adds the `IfTAPMode` configuration option, which allows selecting TAP mode over TUN mode on supported platforms like Linux.
This option will be ignored on macOS or Windows, as macOS only supports TUN mode with `utun` and Windows with the OpenVPN TAP driver only supports TAP mode. 
Right now there is a problem when selecting TAP mode on Linux and then configuring an MTU larger than `65521` (`65535-14` for the Ethernet headers). A smaller MTU might be required to get around this.
=> Add configuration option for TAP mode

src/yggdrasil/admin.go, src/yggdrasil/router.go, src/yggdrasil/session.go, src/yggdrasil/wire.go, yggdrasil.go
Extends the session pings to include the MTU of each endpoint. The `sessionInfo.getMTU()` function returns the lowest of the two MTUs. In the event that a node does not report an MTU, or tries to report an MTU smaller than the IPv6 minimum MTU size (1280), it is assumed to be 1280 (to be as "backward-compatible" as possible).
Now that the session MTU is known, it can be used for:
- Ensuring we are not sending oversized packets when using UDP
- Possible MSS clamping or window size tuning with TCP
- Ensuring that we are not writing bigger packets to the TUN/TAP than the operating system expects
It makes sense that the MTU should be configurable to the user, not least because we cannot make assumptions about networks, people may want to bridge the TAP adapter with links of a smaller MTU, …
=> Include endpoint MTU in session pings

src/yggdrasil/icmpv6.go, src/yggdrasil/router.go, src/yggdrasil/session.go
This pull request leverages the previous changes from `icmpv6` and `exchangemtu` to deliver ICMPv6 Packet Too Big messages when a packet sent to the TUN/TAP adapter exceeds the negotiated MTU for a given session.
Given that any Yggdrasil node can now configure their MTU using the `IfMTU` option, the session MTU is automatically selected to be the lower of the two MTUs from either end of the session. This means that the session MTU can vary between different points on the network.
By generating ICMPv6 Packet Too Big messages in response to oversized packets, Path MTU Discovery in the operating system is able to compensate for this automatically.
=> Implement Path MTU Discovery using session MTU

src/yggdrasil/debug.go, src/yggdrasil/tun.go, yggdrasil.go
Allows Yggdrasil to run without opening a TUN/TAP adapter when `IfName` is set to `none`. Other functions (i.e. peer routing/switching) continue to run normally.
=> Allow setting IfName to 'none' to run without TUN/TAP

.travis.yml, README.md, build, yggdrasil.go
This imports the `minwinsvc` package into `yggdrasil.go` which allows `yggdrasil.exe` on Windows to be run as a Windows service so that it starts automatically with Windows and continues to run in the background.
The `README.md` has been updated in this PR, but in essence the steps to install as a service are:
```
sc create yggdrasil binpath= "\"C:\path\to\yggdrasil.exe\" -useconffile \"C:\path\to\yggdrasil.conf\""
sc config yggdrasil displayname= "Yggdrasil Service"
sc config yggdrasil start= "auto"
sc start yggdrasil
```
This also adds the `-useconffile` option as well as piping configuration into `stdin` with `-useconf`, as it appears `stdin` may not be available for non-interactive processes on Windows.
=> Add support for running Yggdrasil as a Windows service

misc/sim/treesim.go, src/yggdrasil/debug.go, src/yggdrasil/dht.go
Like the title says. There's a DHT maintenance cycle once per second. Previously, each maintenance cycle, the DHT would send two pings. The first was sent to the least recently pinged node (ignoring nodes pinged in the last few seconds, to give them a chance to respond), and the second would cycle through buckets and ping a node from top of the bucket, with a target selected to help fill any holes / bootstrap the DHT. When a node responds to a DHT lookup, up to 2 nodes from the response would immediately be pinged (with their own address as the target, and any nodes in the response are ignored to prevent infinite loops of spam).
The rumor mill does basically the same thing, but instead of pinging nodes, it adds them to a rumor mill. Then, once per second (as the last step of the …
=> Add a rumor mill to throttle dht maintenance traffic

yggdrasil.go
Adds `SIGTERM` to the list of captured OS signals and removes `SIGKILL` which is impossible to catch.
Also adds a function to handle the Yggdrasil service being terminated on Windows.
=> Catch SIGTERM and Windows service termination

src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/session.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/udp.go, src/yggdrasil/wire.go, yggdrasil.go
There's a few different changes in this PR. The highlights are:
1. There's non-backwards-compatible cleanup of a couple of wire packet formats. This removes unnecessary crypto keys from the inner layer of the packets (the keys were already visible in the crypto header, they don't need to be on the inside too) for DHT req/res packets and peer announcement and hop req/res packets. Together, these things reduce the idle bandwidth consumption of the network by some constant but non-negligible factor. **Nodes that fail to update will be unable to communicate with nodes that have.**
2. Peer announcements are throttled. Instead of always being sent 1/second, it checks to decide if it  should send once every second. Every 4th packet is sent, or a packet is sent every time we recognize that …
=> Breaking wire format cleanup and other updates

src/yggdrasil/crypto.go, src/yggdrasil/session.go, src/yggdrasil/udp.go
Changes a few things to try to make PMTU play nicer with UDP links that go over intermediate routers.
1. Removed temporary workaround that set PMTU to at most 2048, now it will default to the smaller tun/tap MTU out of the two end points of a session.
2. When some chunks of a manually fragmented UDP packet fail to make it across (in order), send the parts that were successful instead of dropping them when a new packet comes in, so the end point can receive *something* and try to figure out how to deal with it.
3. When receiving an invalid packet (one that fails at the crypto layer), guess that the packet was missing chunks and reduce the session MTU accordingly, to a minimum of 1280. This *should* eventually find the real MTU of the smallest link that the traffic passes through.
4. Reset …
=> Mostly working PMTU discovery when going over UDP links

src/yggdrasil/admin.go, src/yggdrasil/tun.go
This adds new admin functions for adding peers and modifying the TUN/TAP interface without restarting Yggdrasil. Note that changes made in realtime are **not** written to configuration!
New commands are:
- `addPeer a.a.a.a:b` to add a peer using the default protocol
- `addPeer tcp:a.a.a.a:b` to add a TCP peer
- `addPeer udp:a.a.a.a:b` to add a UDP peer 
- `setTunTap none` to remove the TUN/TAP interface
- `setTunTap auto tun` to configure an unspecified TUN interface with default MTU
- `setTunTap auto tap 1500` to configure an unspecified TAP interface with MTU 1500
- `setTunTap /dev/tap0 tap 1280` to configure a specified TAP interface with MTU 1280
=> Add admin functions for adding peers and modifying TUN/TAP

misc/tests/tunbench-client.go, misc/tests/tunbench-server.go, misc/tests/tunbench.go, src/yggdrasil/admin.go, src/yggdrasil/debug.go, src/yggdrasil/tun.go, src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_linux.go, src/yggdrasil/tun_openbsd.go, src/yggdrasil/tun_other.go, src/yggdrasil/tun_windows.go, yggdrasil.go
Adds support for OpenBSD.
This currently only supports TAP mode, as we don't currently have code to support the Protocol Information header (4 bytes) as this cannot be disabled in TUN mode on OpenBSD.
This code can also be used as a template for supporting other BSDs, although some of the structs and constants may have different orders or values, i.e. `struct tuninfo` is in a different order on FreeBSD.
=> Add support for running OpenBSD

.circleci/config.yml, contrib/deb/generate.sh
This is to add a really simple script to generate a bare-bones `.deb` file for Debian or Ubuntu running on amd64 or i386. The package installs itself into systemd, enables and starts the service on installation. On uninstall, it disables and stops itself.
This is mostly just to make it easier to provide a binary to someone else to test.
To build:
```
PKGARCH=amd64 sh contrib/deb/generate.sh
PKGARCH=i386 sh contrib/deb/generate.sh
```
The resulting `.deb` files can then be taken to a Debian system and installed.
=> Add a script to generate .deb files for Debian amd64/i386

src/yggdrasil/debug.go
If a tun/tap device is launched from debug.go, then then there's nothing to handle any errors that the read or write functions may return. In such cases, if these functions return an error, then the program would silently enter a broken state.
This *shouldn't* happen, but if it does, use panic to throw the error and crash the program with a traceback. This is marginally better than silently breaking, I guess... it would be better to handle the error and either log that there was a problem, or just restart the read/write loop, but I'm not sure what the best course of action is. I guess for now, just panic, and if it ever runs into this problem for a non-fatal error, then we can implement better error handling.
=> tun panic if from debug

misc/tests/tunbench-client.go, misc/tests/tunbench-server.go, misc/tests/tunbench.go, src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_freebsd.go, src/yggdrasil/tun_linux.go, src/yggdrasil/tun_other.go, src/yggdrasil/tun_windows.go
This adds support for FreeBSD. Some notable changes from the OpenBSD code include:
1. Different order of `struct tuninfo`
1. Flags not present in `struct tuninfo` for setting interface up and multicast/broadcast vs point-to-point status, although the defaults that FreeBSD picks for this seem to be fine
Currently this only works in TAP mode, as like OpenBSD, the 4-byte protocol information header causes problems in TUN mode. This needs to be fixed in the Water library by determining the packet family from the IP header.
This pull request also includes changing the reference from `neilalexander/water` to `yggdrasil-network/water`.
=> Adds support for FreeBSD

src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_freebsd.go, src/yggdrasil/tun_openbsd.go
This compiles but hasn't been tested yet, so don't pull unless/until that happens. It's mostly for documentatin purposes.
The idea is to merge the common parts of `tun_freebsd.go` and `tun_openbsd.go` into `tun_bsd.go`, and set a `+build` flag to only build it on those platforms, so it doesn't also try to build on darwin. We could probably merge darwin in too, if we either start using SIOCAIFADDR_IN6 to set up the address on all bsd flavors, or fall back to using ifconfig for darwin.
=> Deduplicate some BSD code

src/yggdrasil/tun.go, src/yggdrasil/tun_bsd.go
Since we're not using tunInterface, and we have our own fork of water anyway, just directly use water.Interface for everything. We can always change it back later if we need to. This lets us get to the ReadWriteCloser, which we can cast to an `*os.File` and ask for the `Fd()`. Untested but I think it should work.
=> Don't use water.Interface.FD()

.circleci/config.yml, README.md, src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_freebsd.go, src/yggdrasil/tun_netbsd.go, src/yggdrasil/tun_other.go
This code actually consolidates a lot of the BSD code together, and even setting the interface MTU with SIOCSIFMTU seems to work fine.
What doesn't work though is setting the interface address using SIOCSIFADDR_IN6 (therefore issue #37 still remains), which I attempted to plagiarise from the Darwin code.
As a fallback, ifconfig is used, which solves the problem enough to get it working.
=> Attempt to support NetBSD

.circleci/config.yml, contrib/deb/generate.sh, contrib/semver/name.sh, contrib/semver/version.sh
Fixes issue #45 by introducing semantic versioning.
The format is `X.Y.Z`, where `X` and `Y` are derived from tags of format `vX.Y` and `Z` is derived from the number of commits since the last tag.
=> Use semantic versioning (fixes #45)

src/yggdrasil/tcp.go, src/yggdrasil/udp.go
Currently only the TCP listen address is printed to stdout, as identified in #51. This PR adds the UDP listen address too.
Example output with `-autoconf`:
```
2018/03/07 09:19:35 Listening for TCP on: [::]:62288
2018/03/07 09:19:35 Listening for UDP on: [::]:62865
```
=> Show both UDP and TCP listen addresses in stdout (#51)

yggdrasil.go
Addresses concern in #51 by generating a random port number for `Listen` when running `-genconf`.
For `-autoconf` the listen address is left as `:0` to ensure that the operating system can always pick free ports for autoconfiguration, even if they are not matching.
=> Generate a random port number in -genconf instead of :0

src/yggdrasil/admin.go, src/yggdrasil/debug.go, src/yggdrasil/dht.go, src/yggdrasil/router.go, yggdrasil.go
I think this fixes #54, but I'm not completely convinced this is the right way to do it.
Roughly speaking, the problem is addressed by:
1. Split buckets into `peers` and `other` nodes.
2. Adding a node to a bucket will remove it from both `peers` and `other`, then insert it into one of them.
3. The router occasionally adds a peer to the `peers` side of the appropriate bucket.
4. Nodes we hear about from a dht request/response are only added to the bucket if not already present (already present nodes will get pinged periodically if the bucket is sparsely populated, or else pushed out by new nodes eventually, with peers sticking around forever--hopefully).
This means that a node added as a peer *should* only appear in peers. Remaining edge case issues/weirdness are:
1. If a node is added as …
=> DHT peers/other partitioning

src/yggdrasil/icmpv6.go, src/yggdrasil/router.go
Previously the source address of this ICMPv6 message was a link-local address, which was fine to responding to the host running Yggdrasil, but would not be routable to any hosts behind it (i.e. when using a routable Yggdrasil /64 subnet).
The new source address for the "Packet Too Big" messages is the routable `fd00::/8` destination address of the oversized packet, allowing it to be routed properly.
The source address of NDP messages is unchanged and continues to be link-local.
=> Modify ICMPv6 source address for "Packet Too Big" messages

contrib/macos/yggdrasil.plist
The launchd script can be used to run Yggdrasil as a service on macOS. It assumes that the Yggdrasil binary is `/usr/bin/yggdrasil` and the configuration is in `/etc/yggdrasil.conf`. 
Install the script:
```
sudo cp contrib/macos/yggdrasil.plist /Library/LaunchDaemons/
```
Enable the service:
```
sudo launchctl load /Library/LaunchDaemons/yggdrasil.plist
```
Disable the service:
```
sudo launchctl unload /Library/LaunchDaemons/yggdrasil.plist
```
=> Add launchd script for macOS to contrib

.circleci/config.yml, contrib/deb/generate.sh
This adds ARMv7 `armhf` targets for CircleCI Linux builds.
I don't know exactly which ARM devices this target will support but it aligns against the Debian `armhf` architecture. Debian also has `arm64` which we should look to support separately.
=> Add armhf target for CircleCI

src/yggdrasil/dht.go
All DHT pings currently happen by adding nodes to a rumor mill, and then pinging 1 node/second from the mill.
There are 3 ways in which nodes can be added to the mill:
1. Any time we ping a node in the DHT, we ask for a target, and they respond with the nodes closest to that target. We add these nodes to the rumor mill (this is how we learn about nodes that aren't already in our DHT).
2. During the maintenance cycle (1/sec), if the mill is empty, we add the oldest node in the DHT to ping them (to check that they're still working).
3. Also during the maintenance, we cycle through buckets and add a ping to the rumor mill targeting that bucket. This is needed for bootstrapping, and to plug any holes that appear as nodes go offline.
This patch changes cases 2 and 3 to only add a node to the …
=> Limit DHT pings to 1/min per node

src/yggdrasil/debug.go
In response to:
```
panic: parse x.x.x.x:xxx: first path segment in URL cannot contain colon
goroutine 33 [running]:
yggdrasil.(*Core).DEBUG_addPeer(0x8e58000, 0x8e34080, 0x12)
/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/src/yggdrasil/debug.go:317 +0x420
main.(*node).init.func1(0x8e48000, 0x8e58000)
/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/yggdrasil.go:75 +0x70
created by main.(*node).init
/go/src/github.com/{{ORG_NAME}}/{{REPO_NAME}}/yggdrasil.go:69 +0x410
```
=> Default to previous scheme when url.Parse returns an error

src/yggdrasil/admin.go, src/yggdrasil/debug.go, src/yggdrasil/peer.go, src/yggdrasil/tcp.go, src/yggdrasil/udp.go
Fixes #63 and cleans some things up.
The logic in `DEBUG_addPeer` was moved to admin, and the debug function calls admin instead (and panics on error).
The admin's `removePeer` function was changed to accept a port number (which you can see a list of by running `getPeers`) and now also works for TCP (previously mostly-worked for UDP). Most of the logic was moved into `peers.go` and is only called by admin.
Peer structs now have a `close func()` field, which should be set when the peer is being set up in `tcp.go` or `udp.go`, which is called by part of the new peers `removePeer` function. This is set up to either send a close packet (UDP) or close the connection (TCP).
Seems to work, but not especially well tested, so there may be edge cases where things are buggy. In particular, I expect …
=> make removePeers work for TCP connections and minor admin cleanup

src/yggdrasil/admin.go, src/yggdrasil/config/config.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/peer.go, src/yggdrasil/tcp.go, src/yggdrasil/udp.go, yggdrasil.go
This is the backwards and (mostly) forwards compatible part of adding optional authentication to peers.
It adds a `PeerBoxPubs []string` to the config, and a `addAuthBoxPub` to the admin API. When connecting to a peer, the following rules are enforced:
1. Link-local IPv6 is always allowed, unless forbidden by other options in the config (multicast, linklocal).
2. All outgoing TCP (and `socks://...`) is always allowed.
3. Authorized incoming TCP is allowed.
4. Authorized incoming and outgoing UDP is allowed.
5. Other (unauthorized) links are not allowed.
If the list of authorized keys is empty (default), then all traffic is considered to be authorized (the current default behavior).
In addition, traffic from a peer is ignored until a successful switch announcement is received. If no switch …
=> Partial support for authenticated peers

src/yggdrasil/tun_windows.go
Fixes #30 by allowing the `IfName` attribute to be set to an adapter friendly name (as in Network Adapters in Control Panel) on Windows. This way multiple `tap0901` adapters can be used and Yggdrasil can be configured to not conflict with other software using TAP devices on the system.
If the `IfName` is set to `auto`, as is default, the first adapter found is used. 
This has required some modifications to `syscalls_windows.go` and `params_windows.go` in https://github.com/yggdrasil-network/water.
=> Add ability to select specific interface by friendly name on Windows

src/yggdrasil/admin.go
Adds `getTunTap` to the admin socket to get the current name, type and MTU of the TUN/TAP interface.
=> Add getTunTap to admin socket

src/yggdrasil/config/config.go, yggdrasil.go
JSON does not permit comments and may not be the most user-friendly format for the Yggdrasil configuration file.
After exploring YAML, TOML and others, I propose a switch to HJSON. I have made some modifications to the [hjson-go](https://github.com/neilalexander/hjson-go) library to support inserting comments using `struct` tags, and this has also been submitted as a PR for upstream acceptance.
This PR modifies `-genconf` to produce HJSON commented output, and modifies `-useconf` and `-useconffile` to parse HJSON.
It so happens that HJSON is backward-compatible with JSON, therefore existing configuration files should continue to work in the meantime and have done in my limited testing (until some changes are made to address #75 that is).
=> Use HJSON for config instead of JSON

src/yggdrasil/admin.go, src/yggdrasil/dht.go, src/yggdrasil/router.go, src/yggdrasil/search.go
Adds the time since a node was last seen by the DHT (ping response or, in the case of peers, manually inserted by the spanning tree).
Watching the times carefully (`watch "echo getDHT | nc localhost 9001"`), I saw that peers would eventually time out. Tracked it down to a combination of the DHT's `insertIfNew` and `insert` functions. Long story short, new peers could be inserted, but the ping response from an existing peer would never update it's time or reset the missed ping counter to 0, so they would eventually get dropped and re-added. Now, peers get added as normal nodes in the bucket, unless the bucket is already full with other/better nodes. If it's already full, then they get inserted into the separate bucket.peers slice, and get re-inserted every time the tree tries to update …
=> More DHT updates

src/yggdrasil/admin.go, src/yggdrasil/router.go, src/yggdrasil/session.go
This exposes three new fields to the `getSession` admin socket call:
- `bytesSent` shows the number of real traffic bytes sent over a session (not including overheads)
- `bytesRecvd` shows the number of real traffic bytes received over a session (not including overheads)
- `wasMTUFixed` shows if the MTU had to be adjusted to a lower value as a result of read errors
=> Track TX/RX bytes over session and if MTU was adjusted, adjust MTU exchange behaviour, send session pings on TUN/TAP change

src/yggdrasil/admin.go, src/yggdrasil/peer.go
This is a mostly-trivial change to add a peer's uptime and bytes sent/received to the response of getPeers (and start tracking those things in the `peer` struct).
It's *technically* wrong, since it's possible that a packet could drop after `peer.sendPacket(packet)` is called and before it gets written to the wire, but that should be uncommon in practice. We can move the code there and change the internal workings at some point if it makes sense to do so. Note that it's also missing a little padding from the TCP stream (4 bytes + a variable packet length) and application-level UDP packet headers (3 bytes per chunk), as well as transport and IP overhead per packet, since those are harder to account for. I think these *should* be small, relative to typical packet sizes, but it means the …
=> Add uptime and bytes sent/recvd to  the `peer` struct and getPeers results

src/yggdrasil/admin.go, src/yggdrasil/core.go, yggdrasil.go, yggdrasilctl.go
This is a very minor fix to expose the IPv6 address and subnet from `Core`, which allows both to be displayed on stdout at startup.
This is really just for user-friendliness.
Sample output:
```
2018/05/21 16:15:13 Your IPv6 address is fd00:baf1:6864:d945:1f44:b820:6bb5:98a7
2018/05/21 16:15:13 Your IPv6 subnet is fd80:baf1:6864:d945::/64
```
=> Show IPv6 address and subnet on startup

contrib/deb/generate.sh, misc/sim/treesim.go, src/yggdrasil/admin.go, src/yggdrasil/config/config.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/multicast.go, src/yggdrasil/peer.go, src/yggdrasil/tcp.go, src/yggdrasil/udp.go, yggdrasil.go, yggdrasilctl.go
This PR makes various changes:
- Updates the configuration names, which resolves #75
- Checks whether old configuration names are present in the configuration file, maps them to the new configuration names and warns the user (this behaviour will want to be removed in the future)
- Adds a `-normaliseconf` option which takes configuration from `-useconf` or `-useconffile` and converts it to HJSON with the correct key names
- Moves the multicasting into the `yggdrasil` package instead of `yggdrasil.go`
- Makes `MulticastInterfaces` a list of regexes, which controls which interfaces are used for multicasting
- Ignores interfaces that are point-to-point, down or not multicast-enabled when selecting interfaces
- Disables multicasting if `MulticastInterfaces` is an empty list
=> Update configuration names and update multicast behaviour

contrib/deb/generate.sh
This fixes a bug in the Debian `postinst` script where the config does not normalise properly, resulting in a new configuration overwriting the old one.
=> Fix debian normalisation in postinst

src/yggdrasil/admin.go, yggdrasilctl.go
This adds the IPv6 subnet to the `getSelf` lookup, and adds pretty `getSelf` formatting to `yggdrasilctl`.
This also adds `getMulticastInterfaces`, which shows which interfaces multicast peer discovery is active on, and pretty formatting in `yggdrasilctl`.
=> Add getMulticastInterfaces and getSelf to yggdrasilctl

src/yggdrasil/multicast.go, src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_darwin.go, yggdrasil.go
This fixes a couple of bugs:
- Since `MulticastInterfaces` works by using `append`, the `MulticastInterfaces` must be empty by default or else multicast cannot be disabled. Beforehand, `.*` was always being added to the default configuration. This fixes this.
- On macOS, IPv6 addresses ending with `8` would be truncated by a faulty `strings.TrimRight` statement. This has been fixed.
=> Fix MulticastInterfaces and accidental truncation of addresses on macOS/BSD

src/yggdrasil/debug.go, src/yggdrasil/udp.go, yggdrasil.go
When loading a config file through hjson, convert it to json and then load the json into the config struct. This correctly allows missing values to take on the defaults normally associated with genconf.
=> hjson bugfixes

src/yggdrasil/admin.go
The dot graph is a little bland. It shows you the nodes you know about, but says nothing about why you know them.
This change styles nodes differently based on why we know them. Currently they're colored as follows: nodes that we only know about because we have an active session are red, nodes we have in the DHT are blue, peers are green, the self node is white, and anything missing but inferred (`?`) is shaded.
I have no idea if that's something we want. If it is, then I have no idea if these color choices are appropriate (we should make sure that the text is easy to read, including for people with abnormal color vision, and maybe introduce a shape difference too).
=> Admin "dot" style changes

src/yggdrasil/tun.go
This was broken during the de-debug PR #96, and is now fixed.
=> Fix IfName 'none'

src/yggdrasil/admin.go, src/yggdrasil/multicast.go
Replaces `m.interfaces` with `m.interfaces()` that builds the list of multicast-allowed interfaces on-the-fly. This allows multicast to work on interfaces that come up after yggdrasil has already started.
I believe this was how it worked when the code was in `yggdrasil.go`, but I didn't notice the change until I started re-running some old tests with netns while working on another PR.
=> Enable multicast on interfaces that come up after startup

misc/sim/treesim.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/dht.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/search.go, src/yggdrasil/session.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/wire.go
Note that this PR is *not* backwards compatible, so it's requested for `develop`, and shouldn't hit `master` until the v0.2 release.
This is a whole mess of changes related to using a new switchMsg format.
Previously, we had 3 packet types related to the switch / spanning tree. There were announcements, hop requests, and hop responses. The announcements listed some basic info about a node's coords (including a sequence number and the number of hops to the root), and the node's peers would send hop requests and get back hop responses until they had all the information they needed. `wire_LinkProtocolTraffic` packets bypass the LIFO queue in `tcp.go`, to make sure they aren't dropped due to congestion, and to avoid races with later traffic packets.
That made sense when we wanted to send tiny …
=> Use new switchMsg format

yggdrasil.go
Plays nicer on platforms where `localhost` doesn't resolve to `[::1]`.
=> Use "localhost:9001" for the default admin socket

src/yggdrasil/tcp.go, src/yggdrasil/version.go, src/yggdrasil/wire.go
Fixes #42 to the extent that I think we can/should address it for now. Things are not forwards/backwards compatible, but this should catch incompatible versions at connection setup time, close the connection, and print a print (or spam, if reconnection attempts are made) a notification to the logs that newer version was seen.
The first 4 bytes ('meta' header) and first uint64 (major version number) are meant to be kept in the same format across version changes. The rest of the metadata (minor version, keys) can be changed in future versions, or change to signal that something in the wire packet formats have changed. We would probably want to remove the minor version number field for the stable 1.0+ releases, if/when that happens.
There's also a minor bugfix to wire signed int formats (the …
=> Add version information to connection setup

src/yggdrasil/admin.go, src/yggdrasil/core.go, src/yggdrasil/crypto.go, src/yggdrasil/dht.go, src/yggdrasil/icmpv6.go, src/yggdrasil/multicast.go, src/yggdrasil/peer.go, src/yggdrasil/release.go, src/yggdrasil/router.go, src/yggdrasil/search.go, src/yggdrasil/session.go, src/yggdrasil/signature.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/tun.go, src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_linux.go, src/yggdrasil/tun_windows.go, src/yggdrasil/util.go
Cleans up import statements and removes some old commented-out code.
It also uses the helper functions from `address.go` instead of checking for `0xFD` in `icmpv6.go`, which *should* work (they're used in `router.go` for the same purpose), but I haven't tested it.
=> Code cleanup

contrib/deb/generate.sh, contrib/macos/yggdrasil.plist
Makes the launchd file for macOS refer to `/usr/local/bin` instead of `/usr/bin`, since `/usr/bin` is protected by System Integrity Protection and can't be written to/installed in very easily.
Also amends the Debian control file to include a `Replaces:` statement so that `yggdrasil` and `yggdrasil-develop` can be installed on top of one another. Also fixes the URLs in some of the metadata files to point to the org repository.
=> Fix launchd script path and amend debian control file

src/yggdrasil/address.go, src/yggdrasil/admin.go, src/yggdrasil/core.go, src/yggdrasil/icmpv6.go, src/yggdrasil/tun_darwin.go
Previously: used `fd00::/8`, with `fd00::/9` for nodes and `fd80::/9` for `/64` subnets.
Now: uses `0200::/7`, with `0200::/8` for nodes and `0300::/8` for subnets, to avoid conflicts for people already using ULA in their networks. The `0200::/7` range was reserved in [rfc1888](https://tools.ietf.org/html/rfc1888) and deprecated in [rfc4048](https://tools.ietf.org/html/rfc4048), and appears to have not been reassigned for any purpose yet, so we think it's safe to squat here for now.
We can always change the address range later. NodeIDs are used internally, so only the edges of the network need to update for new addressing schemes to work.
Tested on linux, and I think I've updated the required parts for macos. I think other platforms *should* work, but testing would be good. The main issue …
=> Address prefix change

yggdrasil.go
This was a typo that would have affected detecting a BOM for big-endian UTF-16.
This didn't affect Windows as it seems to rather tightly stick to little-endian.
Thanks @cathugger for pointing this out!
=> Fix typo for big-endian BOM

build
These updates cause the build script to strip the binary by default, unless producing a debug build.
This also adds two flags to `build`:
- `-d` for debug builds (doesn't strip and adds `-tags debug`)
- `-u` for UPX packing, if available on the system
=> Update build script

src/yggdrasil/router.go, src/yggdrasil/session.go, src/yggdrasil/signature.go
Currently, when creating a new session, we first loop over all existing sessions and clean up any timed-out ones. This is probably bad if there's a lot of open sessions and large numbers are created/destroyed.
This change removes the cleanup from createSession, and instead runs cleanup periodically (once per minute, which is also the time between session timeouts). It does something similar with cached checked signatures, which were using a similar logic (but at least had a timeout between cleanup attempts before).
=> Sesson cleanup

src/yggdrasil/admin.go
This simplifies `addAllowedEncryptionPublicKey` and `removeAllowedEncryptionPublicKey` by changing the key name `box_pub_key` to `key`.
=> Change box_pub_key to key in admin API

misc/run-schannel-netns, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/peer.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go
These changes give a more realistic implementation of backpressure using only local information.
Switch lookup logic has been moved to a dedicated switch worker goroutine, which does basically 2 things:
1. When a packet comes in, it checks all idle peers, and sends the packet to the one that's the best next hop, if a valid next hop exists. If no next hop exists, the packet is buffered, with overflowing buffers dropping in FIFO order.
2. When a connection to a peer notifies the switch that it's idle (i.e. able to send something), the worker loops over the buffers and finds the smallest non-empty buffer for which the peer is a valid next hop, and sends a packet from the buffer (FIFO). If it can't find a packet, it adds the link to the idle set (to be used by 1).
Separate buffers are …
=> Local backpressure improvements

src/yggdrasil/switch.go
Previously, we kept an arbitrary amount of information in the backpressure buffers, but removed anything older than 25 ms. That time is both arbitrary and needs work tuning.
This patch set changes the following:
1. Track queue sizes in terms of bytes instead of number of packets.
2. Limit the total size of all queues to 4 MB. If the queue sizes get larger than this limit, the first packet from a random queue is dropped, with odds based on relative queue sizes, until the total drops below 4 MB. The 4 MB threshold is arbitrary, but I think it's a reasonable size for now. We could either make this configurable, or adjusted at runtime based on e.g. number of peers, at some later point.
3. When deciding which queue to send from, select the one that maximizes `<age of oldest packet>/<size of …
=> Limit backpressure resource consumption

src/yggdrasil/admin.go
This falls back to trying TCP in the event of `AdminListen` scheme parsing failing - i.e. `localhost:9001` will detect `localhost` as the scheme and fail. This might break some old configs or expected behaviour if changed, so falling back to TCP is better than failing altogether.
=> Fallback to TCP when parsing AdminListen

src/yggdrasil/debug.go
There were some calls to the old `getDefaults` in `debug.go` which were not highlighted by CircleCI - it doesn't currently test debug builds.
This PR fixes those calls, allowing the sim, genkeys etc to be built.
=> Fix debug builds after changes in #155

src/yggdrasil/tun_linux.go, src/yggdrasil/tun_windows.go
On Linux, the maximum MTU ordinarily is 65535 for TUN devices, but it appears that TAP devices also account for the 14 byte ethernet header, making 65521 the maximum MTU for TAP.
Beforehand, if you had the `IfMTU` setting as higher than 65521 and enabled `IfTAPMode`, Yggdrasil would panic at startup with an `invalid argument` error.
This patch caps the TAP MTU to 65521 so that it starts correctly. It does not affect TUN.
=> Cap MTU on Linux in TAP mode

.circleci/config.yml, contrib/deb/generate.sh
This adds a new `arm64` target to the Debian build script, and configures CircleCI to build it.
=> Create arm64 builds for Linux

src/yggdrasil/admin.go, src/yggdrasil/tun_linux.go
Previously, when running dot over the api, links were sorted by destination node coords, with the coords already in a string format. Now they're sorted by the integer value of the last hop in the coords, so `10` is added to the graph after `2`. This leads to a better layout in the resulting image if you run `yggdrasilctl dot | dot -Tsvg -o network.svg` or similar.
=> Sort dotgraph links by integer value

src/yggdrasil/session.go, src/yggdrasil/switch.go
Packets in the switch are tagged with a stream id, which determines which queue they end up in.
Previously, this was some combination of packet type, coords, and handle (for session traffic) or keys (for protocol traffic). Now it's just equal to the coords.
Meanwhile, in the session worker that encrypts outgoing packets, coords are appended with `0x00` (to make sure they always get routed to the destination node's self peer -- aka the router), followed by some arbitrary data to put different streams of traffic into different queues. Currently, this is the IPv6 header's next header field (typically this indicates a TCP or UDP header is next), followed by the first two uint16 from the next header (source and destination port for TCP and UDP), with all of these things being converted to a …
=> StreamID changes

src/yggdrasil/config/config.go, src/yggdrasil/core.go, src/yggdrasil/tcp.go, src/yggdrasil/tun_linux.go
This should be helpful on high-latency networks, like Tor or I2P.
Also gofmt.
=> Make TCP read timeouts configurable.

doc/Whitepaper.md, src/yggdrasil/debug.go
Updates whitepaper to make it a little more readable. This mostly uses info from the old version of the about page on the .io site. There's more to do, but at least now the paper shouldn't be completely useless (and the info it does have should reasonably well reflect the current state of things).
Also fixes a compile error with debug builds.
=> Whitepaper

src/yggdrasil/admin.go
This fixes a stupid bug I introduced in an earlier patch. In the dot graph, links to unknown (`?`) nodes were keeping a default (0) value for the port number attached to the link. This patch sets labels on these links to the correct values.
=> Fix bug in admin dot graph

src/yggdrasil/admin.go, src/yggdrasil/config/config.go, src/yggdrasil/core.go, src/yggdrasil/multicast.go, src/yggdrasil/tcp.go, yggdrasil.go
This adds support for a new configuration option `InterfacePeers` (in addition to `Peers`, not replacing). It allows adding a peering specifically on a given interface, and to create redundant peerings over redundant network links.
It scans the interface for the first unicast address that matches the protocol (IPv4 vs. IPv6) and then uses that as the source address for the TCP dial.
The changes to the configuration look like this:
```
InterfacePeers: {
"en0": [ "tcp://172.22.97.1:5190" ]
"en1": [ "tcp://172.22.97.1:5190" ]
}
```
This will have no effect on SOCKS5 peers, which will continue to use the standard default source address. 
It also adds the optional `interface=` option to `addPeers` on the admin socket, and adds `bytes_sent` and `bytes_recvd` to `getSwitchPeers`. (Currently …
=> Support adding peers on specific interfaces

src/yggdrasil/tcp.go
This fixes a bug where an `InterfacePeers` entry with a source interface that doesn't exist doesn't get ignored properly.
=> Ignore peer in InterfacePeers when source interface not found

.circleci/config.yml, src/yggdrasil/debug.go
Debug builds were broken by #182 due to the change of parameters in `admin.addPeer`. This PR fixes this.
It also changes the CircleCI builds to use Go 1.11 instead of Go 1.9, and tests that the debug builds are working before continuing onto non-debug platform builds.
=> Fix debug builds

src/yggdrasil/admin.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, yggdrasilctl.go
This adds `getSwitchQueues` in order to find out information about the switch queues, i.e.
```
$ yggdrasilctl getSwitchQueues
Total queue count: 1
Total queue size: 1049472
Maximum queue count: 2
Maximum queue size: 1377432
Active queues:
- Stream ID: [8 3 2 0 239 191 189 239 191 189 10], size: 1049472, packets: 16
```
To do this, `switch_buffers` are moved into `switchTable` to make them accessible from a newly-created switch admin function, which takes a lambda to run on the switch worker goroutine.
At the moment these numbers are switch-wide - it will be interesting to try to determine pressure at a switchport/peering level in the future.
=> Add getSwitchQueues

src/yggdrasil/peer.go, src/yggdrasil/switch.go
With any luck, this will fix the bug that @MakeItGreatAgain reported with crashing under load when goroutines are running across CPU cores.
https://ban.ai/~jhj/misc/yggdrasil-crash-0928.txt
=> Fix a concurrent map read-write when removing peers

src/yggdrasil/config/config.go, src/yggdrasil/core.go, src/yggdrasil/peer.go, src/yggdrasil/search.go, src/yggdrasil/session.go, src/yggdrasil/tcp.go, yggdrasil.go
The session firewall is designed to control who you can exchange session traffic with. It lets you limit it based on whether the peer is direct, remote, listed in a whitelist or listed in a blacklist. It defaults to being disabled (that is, allowing all session traffic to pass).
The only thing I'm not particularly satisfied with is that currently this works by simply ignoring the session ping, so the session never actually gets created at all, whereas setting `IfName` to `none` allows the session to open anyway and sets an MTU of 0 whilst still preventing traffic flow. I am not sure which behaviour is better.
It adds the new default config:
```
SessionFirewall:
{ 
Enable: false
AllowFromDirect: true
AllowFromRemote: true
AlwaysAllowOutbound: false
WhitelistEncryptionPublicKeys: [] …
```
=> Add session firewall

.circleci/config.yml, contrib/macos/create-pkg.sh
This helps CircleCI to create .pkg installer files for macOS that installs `yggdrasil` and `yggdrasilctl`, generates an `yggdrasil.conf` if it doesn't already exist, and installs Yggdrasil into `launchd`.
=> Add create-pkg.sh for creating macOS installers

src/yggdrasil/ckr.go, src/yggdrasil/config/config.go, src/yggdrasil/core.go, src/yggdrasil/router.go, src/yggdrasil/session.go, src/yggdrasil/tun.go
This PR allows non-Yggdrasil subnets to be routed over Yggdrasil. It allows for specific subnets to be routed to a specific public key (`IPv4Destinations` and `IPv6Destinations`) and allows specifying valid source addresses for crypto-key-routed traffic (`IPv4Sources` and `IPv6Sources`).
=> Tunnel traffic using crypto-key routing

src/yggdrasil/icmpv6.go, src/yggdrasil/tun.go
This changes the behaviour of ND in TAP mode by:
1. Learning MAC addresses through ND advertisements
2. Requesting the host MAC address through ND solicitation when it is not known at startup
3. Selecting the correct MAC address for traffic received before sending to the TUN
4. Unique link-local address and MAC address based on the first few bytes of the node's public encryption key
This *should* in theory allow bridging the TAP adapter for the routed `/64` subnet and should also fix cases where TAP required the node to send some traffic to learn the MAC before received traffic could be routed correctly.
=> Neighbor discovery changes for TAP mode

misc/sim/treesim.go, src/yggdrasil/dht.go
This fixes the sim to work again after the ckr changes, and adjusts which nodes appear in DHT lookup responses a little bit, which should make it bootstrap a bit faster (based on a few tests in the sim). A DHT full of these nods *may* give slightly more useful lookup responses to nodes running the old kad DHT.
=> Tune DHT a little better

src/yggdrasil/admin.go, yggdrasilctl.go
This PR makes a number of clean-up changes to the admin socket:
- Using `box_pub_key` instead of `key` and `destPubKey`
- Sending `box_pub_key` with `getPeers`, `getSwitchPeers`, `getSessions`, `getSelf`
- Renames `help` to `list`
- Adds `-v` verbose output to `yggdrasilctl` which includes keys (hidden by default)
=> Admin socket clean-up

yggdrasil.go
This adds the `-json` flag as an option for `-genconf` and `-normaliseconf`.
We already have the ability to parse normal JSON as well as HJSON - this just makes it easier to clean up the configuration into standard JSON format without comments etc.
Example:
```
yggdrasilctl -genconf -json
yggdrasilctl -useconffile /etc/yggdrasil.conf -normaliseconf -json
```
=> Add -json flag for -genconf and -normaliseconf

src/yggdrasil/multicast.go, src/yggdrasil/multicast_other.go, src/yggdrasil/multicast_unix.go, src/yggdrasil/multicast_windows.go
This PR aims to fix #222 by setting `SO_REUSEPORT` (or `SO_REUSEADDR` on Windows) on the multicast socket. This allows multiple Yggdrasil process to run side-by-side with multicast support enabled, as long as the `Listen` and `AdminListen` directives are configured differently on each instance.
Currently this only adds support for Linux, Darwin, Windows and the BSDs. On other platforms (Solaris, Plan9) nothing is done and reusing the multicast socket will fail in the usual way.
This PR does use `ListenConfig` which I believe is only present in Go 1.11, so we may be tying ourselves to requiring Go 1.11 to build Yggdrasil. I don't suppose this is a problem, and we may already do that in other places, but worth mentioning regardless.
=> Try to SO_REUSEPORT on multicast socket

CHANGELOG.md, src/yggdrasil/switch.go
Fixes two bugs in the switch:
1. A bug introduced in the switch latency changes, where some info was being reset in cases were it shouldn't be, which would (probably) have cause unnecessarily flapping in the event that the root goes offline or a common ancestor of all peers changes coords.
2. Fixed a bug where, if a peer keeps a connection alive, but doesn't send any switch traffic, then the peer will stay in the switch table indefinitely. They will now be removed from the switch table if they fail to respond for 1 switch timeout period, + a little extra time in case they weren't responding because they had no path to the root (e.g. one of their ancestors, or the root, went offline or broke a link). For non-malicious peers, this is most likely to be an issue if `ReadTimeout` is set to a …
=> switch bugfixes

build, cmd/yggdrasilctl/main.go, contrib/deb/generate.sh, contrib/macos/create-pkg.sh, contrib/semver/version.sh, src/yggdrasil/admin.go, src/yggdrasil/core.go
This gives us a "bare" version number, i.e. `0.2.7-0089` instead of `v0.2.7-0089`, which looks a bit nicer in `-version` and `getSelf` etc. This may also be useful in some packaging cases.
=> Strip v from version during imprint

CHANGELOG.md, src/config/config.go, src/yggdrasil/admin.go
This small PR allows you to disable the admin socket for security reasons by setting `AdminListen` to `"none"`.
=> Allow disabling admin socket

build
Adds new options to `build` for the following:
- `-t` keeps symbols and DWARF tables
- `-c` specifies `GCFLAGS`
- `-l` specifies `LDFLAGS`
This allows us to do things we couldn't before, like `./build -t -l "-linkmode=external"` for satisfying `rpmbuild`.
=> Add -t, -c and -l to build script

CHANGELOG.md, contrib/rpm/yggdrasil.spec
This is an example, but incomplete, way that we can create a source RPM package for Yggdrasil.
Assuming `rpmdevtools` and `rpmbuild` installed, and that `yggdrasil.spec` has been updated to reflect the correct version, paths etc.
1. Run `rpmdev-setuptree`
1. Copy `yggdrasil.spec` into `~/rpmbuild/SPECS`
1. Download the `.tar.gz` source file from `Source0` in `yggdrasil.spec` into `~/rpmbuild/SOURCES`
1. From `~/rpmbuild/SPECS`, run `rpmbuild -bs yggdrasil.spec` to build the source RPM
1. Run something like `rpmbuild --rebuild ../SRPMS/yggdrasil-0.3.0-1.fc29.src.rpm` to build the binary RPM
This currently doesn't do anything to back up and normalise the configuration during upgrades like the current Debian package does, but there do seem to be some helper macros for handling the systemd …
=> Add starting point for an RPM spec file

CHANGELOG.md, cmd/yggdrasilctl/main.go, src/defaults/defaults.go, src/defaults/defaults_darwin.go, src/defaults/defaults_freebsd.go, src/defaults/defaults_linux.go, src/defaults/defaults_netbsd.go, src/defaults/defaults_openbsd.go, src/defaults/defaults_other.go, src/defaults/defaults_windows.go, src/yggdrasil/admin.go
This PR contains the changes needed to switch to UNIX sockets for the admin API by default on supported platforms.
=> Use AF_UNIX socket by default for admin API

contrib/deb/generate.sh
It now won't enable itself automatically on install and it will only start Yggdrasil if it was previously enabled in systemd. It also won't break during install on systems where systemd is not present.
=> Update debian package behavior

cmd/yggdrasil/main.go, src/yggdrasil/adapter.go, src/yggdrasil/admin.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/icmpv6.go, src/yggdrasil/router.go, src/yggdrasil/session.go, src/yggdrasil/tun.go, src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_linux.go, src/yggdrasil/tun_other.go, src/yggdrasil/tun_windows.go
This is a refactoring exercise.
So far:
- `tunAdapter` (previously `tunDevice`) moved into `router` from `Core` (in preparation of potentially having more adapters attached to the router, e.g. for API access
- `tcp://` formatting is added to old-style peer entries in `-normaliseconf` and no longer in `addPeer`
- Defines an `Adapter` base type and interface for router adapters
- Modify `tunAdapter` so that it's now based on the `Adapter` base type
=> Refactoring

cmd/yggdrasilctl/main.go
This fixes the bug where `-endpoint` gets ignored by accident.
=> Fix bug in yggdrasilctl where -endpoint gets ignored

cmd/yggdrasil/main.go
This fixes a panic at startup if `Peers` or `InterfacePeers` are commented out. This was introduced by the new code in `cmd/yggdrasil/main.go` which aims to fix the formatting of old peer entries.
=> Fix panic if Peers or InterfacePeers is commented out

src/yggdrasil/peer.go, src/yggdrasil/tcp.go
Does two things right now:
1. Immediately send a switch message when we first connect to a peer.
2. Tell the OS to send TCP keepalive traffic. We currently send application-level keepalive traffic of our own, at least as often as the threshold we give the OS, so this shouldn't actually do anything yet. Long-term, I'd like to switch to having the OS be responsible for this, except in cases where it can't be, since this will let us produce less idle keepalive traffic per peer.
=> Tune peering

src/yggdrasil/tcp.go
Undoes some of the changes from the fastpeer branch because TCP keepalive behavior is platform dependent, and I don't want to deal with that, so we'll have to keep doing things at the application level.
=> Minor TCP change

cmd/yggdrasil/main.go, cmd/yggdrasilctl/main.go, contrib/config/yggdrasilconf.go, go.mod, go.sum
Support for HJSON comments was merged into `hjson-go` in hjson/hjson-go#11 so this updates the `go.mod` etc to point to the master repo again instead of my fork.
=> Point hjson to master repo following comments merge

src/yggdrasil/admin.go
This multithreads the admin socket so that a waiting request doesn't block other requests.
=> Multithread the admin socket

contrib/semver/version.sh
Semver was broken recently by some merge commits. This fixes it.
=> Fix semantic versioning

.circleci/config.yml, contrib/semver/version.sh
This prevents tags from being moved if multiple commits are made on the same release, e.g. to fix a packaging problem.
=> CircleCI: don't recreate tags that already exist

contrib/deb/generate.sh
Support for older raspberry pis and Pi Zero
`armhf` is already used for v7 so `armv6` also sets arch back to `armhf`
Tested On Raspberry Pi B+
=> Added compile support for Arm v6

.circleci/config.yml
This will stop the CircleCI pipeline failing if the tag already exists.
=> Don't fail if tag exists

src/yggdrasil/icmpv6.go, src/yggdrasil/tun.go
This ensures that NDP is not processed when in TUN mode. Ordinarily this shouldn't happen but it does seem to be possible in some very extreme edge-cases, e.g. unusual configuration mixing L2 and L3 interfaces on a router.
=> Don't process ICMPv6 messages when in TUN mode

src/yggdrasil/admin.go
This PR allows you to see your own NodeInfo using admin socket call `getNodeInfo` if you don't specify both `box_pub_key` and `coords`. Beforehand you would have needed to look up your own key and coordinates which was inconvenient.
=> getNodeInfo: Show own info if box_pub_key/coords not specified

contrib/ansible/genkeys.go
It's probably easier to use without it having an ansible folder prefix, if people want to put it into a different dir then they should change their workdir. Apart from that, this fixes a bug where I defined yggdrasil_signing_public_key twice, but never the private key.
=> update ansible key generator

cmd/yggdrasil/main.go, src/yggdrasil/adapter.go, src/yggdrasil/admin.go, src/yggdrasil/ckr.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/dht.go, src/yggdrasil/multicast.go, src/yggdrasil/nodeinfo.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/search.go, src/yggdrasil/session.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/tun.go
This addresses #294 by updating the various `init` functions to use their `Core` reference to obtain the current node config. It also adds the ability to notify each component that the configuration has changed.
=> Use central NodeConfig for components

cmd/yggdrasil/main.go, src/yggdrasil/admin.go, src/yggdrasil/core.go, src/yggdrasil/peer.go, src/yggdrasil/session.go
This adds support for handling `AllowedEncryptionPublicKeys` internally rather than in `cmd/yggdrasil/main.go`.
=> Further nodeconfig changes

contrib/ansible/genkeys.go
Depending on what the parameters are, this is either not faster at all, or *a lot* faster. 
See this benchmark:
```
[jcgruenhage@desperate-nobel yggdrasil-go]$ hyperfine "./genkeysslow -hosts 5000 -tries 8000" "./genkeysfast -hosts 5000 -tries 8000"
Benchmark #1: ./genkeysslow -hosts 5000 -tries 8000
Time (mean ± σ):      5.247 s ±  0.114 s    [User: 5.003 s, System: 0.184 s]
Range (min … max):    5.157 s …  5.553 s    10 runs
Benchmark #2: ./genkeysfast -hosts 5000 -tries 8000
Time (mean ± σ):      2.885 s ±  0.026 s    [User: 2.683 s, System: 0.167 s]
Range (min … max):    2.855 s …  2.945 s    10 runs
Summary
'./genkeysfast -hosts 5000 -tries 8000' ran
1.82 ± 0.04 times faster than './genkeysslow -hosts 5000 -tries 8000'
```
=> make ansible key generator a tiny bit faster

cmd/yggdrasil/main.go, go.mod, go.sum, src/yggdrasil/admin.go, src/yggdrasil/awdl.go, src/yggdrasil/ckr.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/mobile.go, src/yggdrasil/multicast.go, src/yggdrasil/router.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/tun.go, src/yggdrasil/tun_bsd.go, src/yggdrasil/tun_darwin.go, src/yggdrasil/tun_linux.go, src/yggdrasil/tun_other.go, src/yggdrasil/tun_windows.go
This uses the `github.com/gologme/log` package for flexible logging support. It gives us the ability to use "trace", "debug", "info", "warn" and "error" levels in addition to the current `Println`/`Printf` logging we have now. 
I think we possibly only need "debug" and "trace", since we already don't make a lot of other input that's interesting.
=> Add flexible logging support

src/util/util.go, src/yggdrasil/debug.go, src/yggdrasil/link.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/switch.go
The current behavior in `master` and `develop` is to send keep-alive traffic every 4 seconds, and to time out after 6+ seconds (user configurable).
Currently, `link` doesn't time out the connection. Instead, after 6 seconds of inactivity, it stops adding that link to the switch after it sends a packet. That prevents the actual connection from stopping, which gives things more time to recover in light of things like TCP exponential backoff.
This patch changes two things in link:
1. When we receive a packet (with size > 0), we start a timer. If we send a packet back, we cancel the timer. If the timer fires, it means we're idle, and we send a 0-sized keep-alive packet back. This timer is currently hard-coded at 1 second.
2. When we send a packet (with size > 0, so not a keep-alive / ack), we …
=> Idle link logic changes

misc/run-schannel-netns, src/yggdrasil/admin.go, src/yggdrasil/stream.go
3 things:
1. Fix the netns test script (disable admin socket, we don't need it for that test).
2. Fix a nil pointer deref when shutting down if using `"none"` for the admin socket.
3. Remove some unwanted memory allocations that were found by running iperf3 benchmarks between instances running in different netns (particularly allocations that affect intermediate switch nodes).
=> Fix allocations found in profiling

src/yggdrasil/switch.go
If time isn't kept set at the old value when reprocessing existing messages, then it keeps things alive (but in a state where the root is timed out), which seems to break things when leaving hibernate or when the connection between two nodes stops working but never gets closed for some reason.
=> fix bug in switch time

.circleci/config.yml
This stops building 32-bit builds for macOS, as macOS 10.7 was the last OS release to support running on a 32-bit Mac but Go 1.11 requires macOS 10.10.
=> Don't build 32-bit builds for macOS

cmd/yggdrasil/main.go, src/config/config.go, src/yggdrasil/tcp.go
This removes the `ReadTimeout` configuration option as it is no longer relevant following recent switch changes in #322.
This PR also will:
1. Remove the `ReadTimeout` option from the configuration during `-normaliseconf` (which happens automatically during upgrade on some platforms like macOS and Debian)
1. Warn the user in `stdout` that the option has been deprecated if it hasn't been removed from the config by normalisation
=> Remove ReadTimeout configuration option

.circleci/config.yml, src/yggdrasil/multicast.go, src/yggdrasil/multicast_darwin.go, src/yggdrasil/multicast_other.go, src/yggdrasil/multicast_unix.go, src/yggdrasil/multicast_windows.go
This wakes up AWDL for multicast peer discovery when the `awdl0` multicast interface is enabled. This allows Macs to directly peer with one another, even if they are on different Wi-Fi networks or not even connected to Wi-Fi at all.
=> Wake AWDL for multicast peering on macOS

src/yggdrasil/admin.go
If the UNIX admin socket already exists, Yggdrasil will attempt to connect to it. If it responds and connects then the process errors out and exits as the socket is in use. If it doesn't answer then it is assumed that no process is using the path anymore (e.g. because of a crash), therefore we will try to remove it before running `net.Listen`.
=> Try to clean up UNIX admin socket

src/yggdrasil/admin.go
This just adds a 2-second timeout to #356 for safety, in case there is some edge case where we could end up blocking for a long time.
=> Add a timeout on the UNIX admin socket check

.circleci/config.yml
This fixes a problem in the CircleCI workflow for macOS where the `yggdrasil` and `yggdrasilctl` binaries were accidentally omitted from the .pkg file following the refactoring in #350.
=> Fix macOS package

src/yggdrasil/admin.go
This closes #362 by adding `getTunnelRouting` and `setTunnelRouting` to the admin socket to enable or disable tunnel routing:
```
yggdrasilctl getTunnelRouting
{
"enabled": false
}
```
```
yggdrasilctl setTunnelRouting enabled=true
{
"enabled": true
}
```
```
yggdrasilctl getTunnelRouting
{
"enabled": true
}
```
=> Add getTunnelRouting and setTunnelRouting

contrib/busybox-init/S42yggdrasil
I updated the busybox init script with a reload command as HUP reload was added in v0.3.3 :)
+ Added reload command.
+ Use -useconffile instead, as it's required for reloading.
=> contrib/busybox-init: add reload and use -useconffile

CHANGELOG.md, cmd/yggdrasil/main.go, src/config/config.go, src/config/i2p.go, src/config/tor.go, src/util/util.go, src/yggdrasil/admin.go, src/yggdrasil/awdl.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/link.go, src/yggdrasil/multicast.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/tcp.go, src/yggdrasil/tcp_darwin.go, src/yggdrasil/tcp_other.go
This adds support for multiple listeners, e.g. more than one TCP listen address, or in theory mixed types of listeners (e.g. regular TCP sockets, UNIX domain sockets, etc):
1. The `Listen` configuration item is now an array. If it is currently a string then we attempt to convert it to an array either at startup or when running `-normaliseconf`
1. `tcpInterface` is now just `tcp`, in keeping with `awdl`/`awdlInterface`, and it now belongs to `link` rather than `Core`
1. `link` now has a `reconfigure` channel, and it cascades down to `tcp`, `awdl` etc.
1. `tcp` now supports holding and opening multiple listeners
1. The `Listen` configuration item can now be completely empty (e.g. not listening on any globally routable addresses) without affecting link-local multicast (see below)
1. …
=> Support for multiple listeners

src/yggdrasil/multicast.go, src/yggdrasil/tcp.go
This fixes two bugs:
1. The multicast beacons were leaking the interface name from the source machine - although this was irrelevant to the receiver, we now don't leak them
1. The zone was not always being set properly when dialling link-local addresses from multicast, which was resulting in multicast not working when all machines were running the latest `develop` with `multilink` fixes included
=> Fix bugs from multilink branch (#360)

src/yggdrasil/link.go, src/yggdrasil/switch.go
Mark a peer as blocked in the switch if the link's `writeMsg()` call blocks too long.
=> More switch/link fixes

contrib/apparmor/usr.bin.yggdrasil
This PR adds a profile which can be used to harden yggdrasil setup with a Linux kernel security module [AppArmor](https://en.wikipedia.org/wiki/AppArmor).
=> Add AppArmor profile

src/yggdrasil/multicast.go, src/yggdrasil/multicast_darwin.go, src/yggdrasil/multicast_other.go, src/yggdrasil/multicast_unix.go, src/yggdrasil/multicast_windows.go
This fixes AWDL on macOS, which would occasionally not start properly at macOS startup if running as a launchd service. It would also not ever restart AWDL if it was switched off for some reason (e.g. system sleep). We would also keep AWDL awake even if the `awdl0` multicast interface had been removed during runtime.
This now will launch a goroutine on macOS to reevaluate this every minute. We will delete and re-add the browser every minute, which will make sure that AWDL stays alive (it does not switch off straight away when the browser is removed). If `awdl0` is removed from `MulticastInterfaces` then we will not re-awaken AWDL.
=> AWDL fixes for macOS

cmd/yggdrasil/main.go, src/config/config.go, src/yggdrasil/mobile.go
This makes some changes to the `config` package, including updating the default config so that no `Listen` entries are specified by default.
=> Re-order config, update default Listen

CHANGELOG.md, src/yggdrasil/multicast.go
This is an alternative to #382 which makes absolutely sure that we only have one link-local listener per multicast interface, and that we are able to ignore interfaces correctly that don't have a link-local address.
=> Handle cases where link-local addresses may disappear or change

src/yggdrasil/wire.go
Bit operations are much faster on most processors than multiplication.
Also specify that it's zigzag to ease finding additional documentation for it.
=> wire: cleaner and faster wire_intToUint and wire_intFromUint

src/tuntap/conn.go, src/yggdrasil/conn.go
There were cases where an error returned by a conn `Read` (e.g. decryption error, invalid nonce) would result in the indefinite blocking of the TUN/TAP reader goroutine since the `read` channel was never written to in those cases.
This PR fixes that, and also stops the connection reader/writer for a given session if the error returned is for a permanent condition.
=> Don't indefinitely block TUN/TAP reader goroutine after conn error

src/tuntap/ckr.go
This should fix a crash which @Mikaela reported trying to determine if CKR is enabled. The panic was as a result of a cast from an atomic load sometimes failing:
```
touko 30 17:10:51 relpda yggdrasil[588]: panic: interface conversion: interface {} is nil, not bool
touko 30 17:10:51 relpda yggdrasil[588]: goroutine 37 [running]:
touko 30 17:10:51 relpda yggdrasil[588]: github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*cryptokey).isEnabled(...)
touko 30 17:10:51 relpda yggdrasil[588]:         /home/circleci/project/src/tuntap/ckr.go:123
touko 30 17:10:51 relpda yggdrasil[588]: github.com/yggdrasil-network/yggdrasil-go/src/tuntap.(*cryptokey).isValidSource(0xc000099c88, 0x0, 0x0, 0x10, 0x0)
touko 30 17:10:51 relpda yggdrasil[588]:         /home/circleci/project/src/tuntap/ckr.go:148 …
```
=> Fix panic when determining if CKR is enabled

src/yggdrasil/conn.go
I think this fixes the issue where sessions mysteriously stop working, due to some keep-alive ping/search traffic that was never being sent. If the fix works, then we should refactor `startSession` a bit so we can directly pass the relevant part to the session worker without going through the router goroutine, since that causes pointless contention. That *shouldn't* be difficult to do, but I'd prefer to deploy a quick fix first and then worry about refactoring.
=> fix issue with sessions dying and never being fixed

src/config/config.go, src/defaults/defaults.go, src/defaults/defaults_darwin.go, src/defaults/defaults_freebsd.go, src/defaults/defaults_linux.go, src/defaults/defaults_netbsd.go, src/defaults/defaults_openbsd.go, src/defaults/defaults_other.go, src/defaults/defaults_windows.go
This changes the defaults to include a platform-specific `MulticastInterfaces` option. This mostly allows us to pick some sane defaults for interfaces we will want to multicast on out-of-the-box.
This mostly arose because using `.*` on macOS includes `awdl0`, which results in waking up the AWDL adapter and dropping other wireless performance somewhat. For someone who isn't aware of what's going on, that could be frustrating.
I don't know the naming conventions for all platforms but this seemed like the least bad way to solve the problem for macOS at least, rather than having specific exceptions for `awdl0` in the config parser.
=> Add multicast interfaces to platform-specific defaults

cmd/yggdrasil/main.go, src/yggdrasil/api.go, src/yggdrasil/session.go
This adds a new API function `SetSessionGatekeeper` which takes a function of type `func(pubkey *crypto.BoxPubKey, initiator bool) bool`. 
The gatekeeper function is called each time a new session is initiated, either incoming or outgoing. The `pubkey` parameter contains the permanent public key of the remote host and the `initiator` function returns `true` if we were the ones to initiate the connection (false otherwise). The function should return `true` if it wants to allow the session or `false` if it wants to reject it.
In addition to this, the session firewall is now implemented in `cmd/yggdrasil` using this new API. This means that `session.go` is a bit leaner now and more complex behaviour can be implemented if required.
=> Implement session gatekeeper functions

cmd/yggdrasil/main.go, src/yggdrasil/api.go
This PR allows you to specify `-logto /path/to/file.log`, `-logto syslog` or `-logto stdout` on the command line, and mostly fixes #396.
This currently doesn't capture the output of panics—I don't know the most elegant to handle that.
=> Add support for logging to file or syslog instead of stdout

src/multicast/admin.go, src/multicast/multicast.go, src/multicast/multicast_darwin.go
This PR updates the `multicast` module to try and be a bit more robust. This should hopefully fix #405 too.
We now try to re-evaluate the available multicast interfaces every minute or on reconfiguration by SIGHUP into a mutexed list of interfaces. We now pay attention to this both when sending and when receiving multicasts, so we don't accidentally hear multicasts and act upon them like we may have done in the past.
I still don't love this module but it'll do for now until we're willing to break protocol and write something better.
=> Try and solidify multicast interface behavior

.circleci/config.yml
This is an attempt to use the new yggdrasil-network/yggdrasil-package-rpm sources to build RPM files. 
Outstanding problems include:
=> Try to build the new RPM using CircleCI

src/util/cancellation.go, src/yggdrasil/conn.go
Since I don't like using the buggy go timers directly, but the go experts want to emphasize that [context isn't for cancellation](https://dave.cheney.net/2017/08/20/context-isnt-for-cancellation), I added a `Cancellation` interface type and a struct with the relevant behaviors to the `util` package. It's more or less like the subset of functions needed for cancellation in with a `context.Context`, except it saves and reports back what `error` (if any) was the reason why it was cancelled, which makes it easier to signal the difference between a timeout and an intentionally closed session.
The `Conn.Read`, `Conn.Write`, and `Conn.Close` functions have all been updated to use this instead of the old `Conn.close` channel. There may be a few deferred `recover()` lines that could safely be …
=> Cancellation

src/yggdrasil/debug.go
This fixes #457 by sending the PPROF output lines to `stderr` instead of `stdout`.
=> Send PPROF output text to stderr

.circleci/config.yml, src/tuntap/tun_darwin.go, src/yggdrasil/search.go
Apparently macOS can't reach itself via its own yggdrasil address, presumably because it sends traffic to the tun instead of using a loopback.
My best guess as to where the traffic gets lost is in the search / DHT lookup step. This change causes the search to initialize with just our own node, instead of the contents of our own DHT. That should force an ordinary DHT lookup to happen, which should fix the search problem, if indeed that turns out to be where the macOS self-traffic gets lost.
Needs testing by someone with a mac.
=> Possible fix for macos self-traffic

cmd/yggdrasil/main.go
The `Listen` directive was changed to a `[]string` in v0.3.6 but proper parsing wasn't in place for non-array values. This fixes #483 so that now Yggdrasil will start correctly and `-normaliseconf` will do the right thing.
=> Transform Listen statement to new format if needed

src/yggdrasil/conn.go, src/yggdrasil/search.go
Not sure if this does anything about #496, since I've been unable to reproduce it, but hopefully it was related the first change.
So the problem here is that searches had 2 ways of exiting without doing proper cleanup:
1. It was plausible that a search may stall if a time variable was checked and found to be slightly too recent (which *shouldn't* happen, with with e.g. instruction reordering etc it's hard to say it can't), so now searches *should* always eventually run the callback with either an error or a success.
2. There was an edge case where a search that failed to set up a session because of a session firewall issue would fail to clean up the old search, which would cause subsequent searches to attempt to continue the old search instead (and ultimately fail).
It also handles ending …
=> Search fixes

go.sum, src/yggdrasil/session.go
Tries to fix 2 issues:
1. If a session is initiated but no listener exists, then the session gets created without no associated Conn, and would never be removed. This leaks memory for nodes that have no tun/tap device (I think, unless there's a dummy listener that I didn't notice).
2. If a listener exists, send the conn to the listener in a separate goroutine instead of blocking the current one. If the listener isn't accepting Conns for some reason, then this will leak sessions (and goroutines stuck on a send) instead of deadlocking the router.
=> Prevent session leaks or blocking if the listener is busy

src/yggdrasil/link.go
This is an attempt to fix the goroutine leak in #501, which involved leaking goroutines from *incoming* connection attempts (note that the goroutine stack begins from the listener accepting an incoming connection).
Now, a goroutine should stick around (blocking further connection attempts) for *outgoing* connections only. Incoming connection attempts shouldn't cause a goroutine leak. There's still some question of why the incoming attempts happen in the first place... perhaps it's nodes running very old/outdated code? I unfortunately don't have a better guess at the moment.
If this continues to leak, then it means we are (for some reason) continuing to attempt outgoing connections when we already have one active. If that happens, then that's a separate bug we should also fix. Duplicate …
=> Try to fix leaks in #501

go.mod, go.sum, src/tuntap/tun_linux.go
This replaces the deprecated `github.com/docker/libcontainer/netlink` library with the newer `github.com/vishvananda/netlink` one.
=> Use new netlink library (fixes #493)

go.sum, src/yggdrasil/switch.go
When there are multiple next hops that a path could take, and they all appear equally good, use the one that's been idle for the *shortest* amount of time instead of the longest.
This should at least be consistent in however it behaves. Currently, it uses the one that was idle the longest, in a round-robin style, but that leads to a lot of packet reordering.
With this change, it's possible that TCP may not throttle up high enough to kick things from a slow link onto a faster link (that's what the round-robin was for), so this isn't a prefect fix, but maybe it's a better default behavior while we search for an alternative.
=> Switch priority change

src/yggdrasil/session.go
Previously, we kept track of the most recently received nonce from a node on the remote end of a session, along with a fixed-size windows of the last 64 possible nonce values, to allow some out-of-order packets to get through without allowing duplicate packets. Nodes skip nonces (one node only sends even nonces, the other only sends odd nonces), so this amounted to a window of 32 packets.
This replaces the fixed size bitmask with a heap (to quickly find the oldest nonce) and a map (to quickly check if a nonce has already been seen, and log the time of when this happened). This is set to keep track of either the last 64 packets, or all packets received in the last 1 second, whichever is larger.
This should be more friendly to packet reordering due to multiple paths and/or congestion …
=> New nonce tracking

src/yggdrasil/debug.go, src/yggdrasil/link.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/stream.go, src/yggdrasil/switch.go
Currently, when a link becomes idle, we check if the switch has any packets buffered that this link could send. If it does, we send 1 packet.
With this change, we collect packets until we either run out of buffered packet to send, or have at least 65535 bytes worth. These are then passed to the link to send all at once (via a `net.Buffers.WriteTo` call that can write multiple packets in one syscall on some platforms).
This should help to reduce syscall overhead when forwarding many small packets. On my machine, if I reduce MTU to 1280, this improves throughput from around 380 Mbps to around 480 Mbps.
=> Send multiple packets from the switch at once

src/yggdrasil/dialer.go, src/yggdrasil/session.go
This should hopefully prevent an edge case where a deadlock could occur, if somehow a session was used without session workers having been started yet, or where a race between a dial and the remote end opening a session could theoretically launch multiple session workers for the same session.
=> hopefully prevent a deadlock

cmd/yggdrasil/main.go, src/config/config.go, src/tuntap/admin.go, src/tuntap/ckr.go, src/tuntap/conn.go, src/tuntap/iface.go
This PR is designed to make CKR clearer, easier to use and more robust.
In summary:
- Configuration options are now renamed:
- `IPv4Sources` is now `IPv4LocalSubnets`
- `IPv4Destinations` is now `IPv4RemoteSubnets`
- `IPv6Sources` is now `IPv6LocalSubnets`
- `IPv6Destinations` is now `IPv6RemoteSubnets`
- Yggdrasil will automatically detect the old configuration item names when reading the config and `-normaliseconf` will rename them correctly to their new names
- Handling of CKR policies in the TUN/TAP adapter is now more robust
- A number of functions in `ckr.go` have been renamed
- Admin socket functions for CKR have been renamed to match the above
=> Cryptokey routing changes

src/yggdrasil/session.go
It was checking the wrong nonce when deciding if it should delete an old known nonce from the heap+map, which was causing it to keep track of old nonces indefinitely if a session stays busy enough.
=> fix memory leak in session nonce map

src/tuntap/tun.go, src/tuntap/tun_windows.go, src/yggdrasil/conn.go
Possibly helps with #471 by adding artificial delay so `netsh` commands have time to take effect before the next one is called. If it really is caused by a race between commands being issued and the tap state changes fully taking effect.
Fixes #490 and #521 (I think).
=> Cleanup and possible bugfixes

go.mod, go.sum
Update to the latest version of `phony` for actor-model stuff and run `go mod tidy` to clean up unused entries from `go.sum`.
The changes in `phony` allow it to stop an `Actor`'s goroutine in the remaining cases where it had one but wasn't using it for anything (namely when it needs to pause due to backpressure). This lets the runtime reuse those resources (goroutine+stack) for other things (like run a different `Actor` if any are scheduled).
=> update phony dependency

src/address/address.go, src/config/config.go, src/crypto/crypto.go, src/util/bytes_mobile.go, src/util/bytes_other.go, src/util/cancellation.go, src/util/util.go, src/yggdrasil/api.go, src/yggdrasil/conn.go, src/yggdrasil/doc.go
This contains various `godoc` documentation updates for the `src/yggdrasil` package so far.
My goal is:
=> Documentation updates

src/yggdrasil/link.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go
So the trick here is, when we receive a packet and have an idle link, don't immediately send to that link. Instead, remove the link from the idle list (as normal), but buffer the packet and launch a new goroutine that will (at some point in the future, at the scheduler's whim) send a message to the switch notifying it of the idle peer. What I hope it does is give the best link a chance to forward that packet and notify the switch that it's idle before the 2nd best link's fake idle notification gets back to the switch. I'm not convinced that it actually does that, but whatever is really happening, it *seems* to help things somewhat in my tests.
Running some tests in network namespaces with artificial latency, this patch seems to help. If a node has 2 links with identical latency, it seems …
=> Switch hack

src/tuntap/iface.go, src/util/cancellation.go
Fixes #553 I think, though it's still a mystery to me why undersized packets would be read in the first place. Adds some trace level logging in the places where we drop packets for being too short, in case we need to monitor this.
=> Packet length checks and logging

src/tuntap/conn.go, src/yggdrasil/conn.go
Fixes #565.
When using CKR, the actor was calling `yggdrasil.Conn.RemoteAddr()`, but this function uses `phony.Block` under the hood, so it could deadlock under load. Some `yggdrasil.Conn` code was rewritten to make sure that the internal state needed for the `RemoteAddr()` call is finalized by the time the `Conn` is reachable by any outside code, so the `RemoteAddr()` implementation can safely read this info without needing to send a message to the actor or block, making it safe for other actors to use.
Theoretically, the same deadlock could happen when we call `yggdrasil.Conn.Close()`, so that now happens in a separate goroutine (since we don't need the return value or care when it finally closes, just as long as it does).
=> CKR deadlock fix

contrib/systemd/yggdrasil.service
- Enable (and limit to) capabilities that require to setup tun/tap interface.
- Ensure that tun module is active.
=> Systemd: tun module and capabilities

go.mod, go.sum, src/yggdrasil/tcp_linux.go, src/yggdrasil/tcp_other.go
Using the bbr congestion control mechanism on linux can massively reduce latency when under load. Ideally, this should be set system-wide with `sysctl -w net.ipv4.tcp_congestion_control=bbr`, but that's seems invasive. This patch uses a sockopt to set bbr congestion control on links to ygg peers.
You still get better performance if the endpoints of a connection have bbr enabled, since then they also react to the full end-to-end bufferbloat (including ygg's internal buffers), but enabling it at the link level seems to give *most* of the benefits (latency is ~25-33% as large as without enabling bbr).
I'm debating whether or not it makes sense to also *optionally* set it system-wide, but set that option to enabled by default, so linux users (with a recent enough kernel) have things "just …
=> Enable bbr for tcp sockets on linux

src/yggdrasil/core_test.go
This pull request adds:
* test for peering connection between two nodes (on localhost),
* test for message transfer between two nodes in both directions,
* benchmark for transfer between nodes.
Tests should be considered sanity checks as they will not direct the developer to the particular point of failure.
Benchmark makes it easy to pinpoint places where performance can be improved when run with `cpu`/`memprofiler` or similar tools.
=> #60 Add simple tests and benchmark

src/yggdrasil/conn.go
Fixes #568 
The `yggdrasil.Conn.search`  function was checking for a non-nil pointer before one of the places the returned session was being used, but not in another, so failed searches could cause a crash. This should now work correctly (I hope, but I'm apparently terrible at writing this one function).
=> fix nil pointer dereference in yggdrasil.Conn.search

src/yggdrasil/search.go
This should fix an issue where a search for an existing session doesn't update the session's coords when the search completes. This can cause the session to enter a broken state if the remote end's coords change.
=> Search bugfix

src/tuntap/ckr.go
The ckr function `getPublicKeyForAddress` was taking the route cache mutex too soon, and then returning without unlocking it if some checks failed (which didn't involve checking anything the mutex was meant to protect). This just moves the mutex use to the point when it's finally required for safety.
=> fix incorrectly held mutex in ckr getPublicKeyForAddress

src/address/address.go, src/tuntap/conn.go, src/tuntap/iface.go, src/tuntap/tun.go, src/yggdrasil/conn.go, src/yggdrasil/dialer.go, src/yggdrasil/listener.go
This PR adjust the `Listener` to return a `(net.Conn, err)` so as to match that part of the `net.Listener` interface. In doing so, the interface of `yggdrasil.Conn` was changed slightly to return `net.Addr` from `LocalAddr` and `RemoteAddr`, and the tun/tap code was updated to type assert things as needed to work with this interface.
Marked as unfinished / work-in-progress since I'm sure there's probably more low-hanging fruit we could add to this (e.g. match the `Dialer` interface too).
=> Have listen and dial return a net.Conn

contrib/systemd/yggdrasil.service
As per #573, this amends `ExecStartPre` to allow failures. This stops a failed `modprobe tun` from preventing Yggdrasil startup in, e.g. OpenVZ containers.
=> systemd: Allow ExecStartPre failures

.circleci/config.yml
This enables Linux armel builds in CircleCI, as per #577.
=> Enable Linux armel builds in CircleCI

src/yggdrasil/api.go, src/yggdrasil/link.go, src/yggdrasil/tcp.go, src/yggdrasil/tls.go
This is an experiment to implement peerings over TLS connections. 
This PR does nothing to Yggdrasil's own encryption, so a peering over TLS actually is encrypted twice. This might have performance penalties.
One thing to be aware of is that there's *absolutely no peer validation whatsoever* at the TLS layer—no certificate validation, no hostname verification, nothing. It's good for steganography (e.g. hiding the fact that it's an Yggdrasil connection) but not much else at this stage.
It works by implementing `TcpUpgrade`, which is a descriptor containing a new protocol name and a function for *replacing* the existing `net.Conn` with a new one that implements other security layers—in this case, `tls.go` replaces the `net.Conn` by wrapping it in a `tls.Conn`.
If no `TcpUpgrade` is …
=> Initial connection upgrade/TLS steganography 

src/yggdrasil/tcp.go, src/yggdrasil/tcp_darwin.go, src/yggdrasil/tcp_linux.go, src/yggdrasil/tcp_other.go
This PR sets `SO_BINDTODEVICE` on linux for peers configured through the `InterfacePeers` option. This *appears* to ensure that packets to/from these peers are not swallowed by the routing table, if e.g. a CKR route is set which overlaps the peer's address range. In particular, I think this should make using CKR as a default route work without needing to manually configure routes to each peer (or carefully construct a routing table that doesn't cover the peers' address ranges).
That's great, but it's linux-specific as far as I know. Apparently macOS already gives the intended behavior, but we may want to look for similar workaround for the BSDs and Windows.
EDIT: one thing to note, `InterfacePeers` applies only to outgoing peers connections. Incoming connections will still obey the usual …
=> BindToDevice

src/yggdrasil/search.go
Fixes a bug found by the race detector.
When a search for an existing session finishes, the router was updating the coords of the session, which could race with the session trying to use those coords for things like sending traffic or session pings.
This fix causes the router to send a message to the session, telling it to update its own coords, instead of trying to directly update the coords on its own.
=> Fix data race

src/yggdrasil/api.go
Fixes #596 (a deadlock from a mutex that wasn't unlocked when `AddPeer` fails). Note that removing a peer from the API doesn't remove it from the internal `Config`, so attempting to add the peer again fails, but at least it doesn't deadlock.
=> fix deadlock when AddPeer fails

contrib/systemd/yggdrasil.service
- Fixed misspelled directive, capability limits now work as expected.
=> FIX: Systemd: typo in directive

src/tuntap/tun.go, src/tuntap/tun_bsd.go, src/tuntap/tun_darwin.go, src/tuntap/tun_linux.go, src/tuntap/tun_other.go, src/tuntap/tun_windows.go
This PR does three things:
1. The handling of MTUs when outside of the acceptable range for the platform is improved
1. Ethernet header bytes are now accounted for in the maximum MTU calculations
1. A warning is now written to `stdout` when the MTU has been changed from the configured value for some reason
This closes #603.
=> Improve MTU handling

src/tuntap/tun.go, src/tuntap/tun_linux.go
This should fix an issue where the MTU adjustment was still not always accommodating for TAP mode correctly. This should close #603 fully.
=> Fix couple of issues with MTU bounds

CHANGELOG.md, src/tuntap/tun.go, src/yggdrasil/api.go, src/yggdrasil/session.go
The problem today is that the `tuntap` module would wrap the MTU down to a sane size but the session code in `Core` wouldn't. This would mean that setting a value larger than 65535 would cause a `uint16` overflow and then traffic wouldn't send over the session.
This adds new API functions for setting the maximum MTU, and then updates `tuntap` to call those as necessary, so that the session code is notified about the *real* TUN/TAP MTU.
For the sake of solving this problem for v0.3.12, I don't plan to make any other big changes, but it probably makes sense to fail hard or ensure that the `NodeConfig` expects a `uint16` rather than an `int` to make these kinds of mistakes more obvious. 
This also removes one of our awful shared-config-struct references, which I will shortly be on a mission …
=> Add API functions for manipulating maximum session MTU

src/multicast/multicast.go
This function always returns nil
Fixed fail execution:
```
go test ./src...
```
vet: src/multicast/multicast.go:110:6: err declared but not used
=> Fix return value in Multicast.Stop()

contrib/msi/build-msi.sh
This should hopefully fix some problems in the MSI with the Wintun driver being incorrectly uninstalled during upgrades and not being reinstalled properly. 
This also sets the compression level higher for smaller downloads and sets the product name to a more friendly name.
=> MSI bugfixes

contrib/systemd/yggdrasil-default-config.service, contrib/systemd/yggdrasil.service
- Modular unit composition: different tasks in separate units
- Use systemd tool set to run checks
- Avoid using inline shell in unit
=> Systemd: move config generation to a separate unit

src/yggdrasil/api.go, src/yggdrasil/nodeinfo.go, src/yggdrasil/router.go
This converts the NodeInfo code to operate around its own actor, rather than the router actor. It also removes all mutexes within `nodeinfo.go` as a result.
The hope is that multiple on-going searches should not block as they do today, which is a big part of why the API server has stopped collecting NodeInfo properly.
=> Actorise NodeInfo

src/util/util.go
ihl may grow upto 15*4=60 so extract and check it before using it as offset in flowkey calculation.
also replace IFs with switches for protocol matching as it's less redundant and nicer to document.
=> util: fix possible OOB in IPv4 flowkey calc, use switch there

src/config/config.go, src/defaults/defaults.go, src/tuntap/iface.go, src/tuntap/tun.go, src/tuntap/tun_bsd.go, src/tuntap/tun_darwin.go, src/tuntap/tun_linux.go, src/tuntap/tun_windows.go, src/types/types.go, src/yggdrasil/api.go, src/yggdrasil/conn.go, src/yggdrasil/session.go, src/yggdrasil/wire.go
The codebase uses int and unit16 to represent MTU randomly. This change
unifies it to a MTU type from types package, which is currently uint16.
Partially fixes #616, didn't want to mix this with MTU correction.
=> Unify MTU datatypes across the codebase

cmd/yggdrasilctl/main.go, src/yggdrasil/api.go, src/yggdrasil/dht.go, src/yggdrasil/nodeinfo.go, src/yggdrasil/router.go, src/yggdrasil/search.go
Just a few relatively small optimizations that seemed like low hanging fruit.
1. `yggdrasilctl` now just calls `os.Exit` on some function, which returns an error code. That allows the internal function to safely use `defer` for cleanup etc, since this happens before the `os.Exit` call causes everything to shut down immediately.
2. In the DHT, always store the 2 closest nodes in each direction around the ring. That way, if your immediate neighbor disappears, you always already know the replacement. This *should* make things a little more robust under node joins/leaves, and *may* speed up bootstrapping a little.
3. The search code has been simplified significantly. Now, instead of storing a list of all visited nodes, we store the single closest node to the destination that we've gotten a …
=> Misc tuning

src/yggdrasil/search.go
This is an old behavior that was dropped during some search tuning, but still seems to improve things (and seems more correct anyway).
=> Sort search response results before sending requests

src/yggdrasil/search.go
Less aggressive searching. This should help with some edge cases where searches send so many packets so fast that they get dropped at the switch layer.
=> More search updates

src/crypto/crypto.go, src/tuntap/conn.go, src/tuntap/tun.go, src/yggdrasil/conn.go, src/yggdrasil/dialer.go, src/yggdrasil/doc.go, src/yggdrasil/listener.go
This adds support for dialling with `"curve25519"` instead of `"nodeid"`, and also updates `RemoteAddr`, `LocalAddr` etc to return public keys instead of node IDs.
=> Use public keys in API functions

src/yggdrasil/dht.go, src/yggdrasil/search.go
EDIT: original patch now in my search-serial branch for backup. This approach keeps the overall behavior closer to what's in master, while still trying to fix the same issues with e.g. getting stuck on dead ends if it comes across an outdated kad node.
In master, we keep track of the closest node visited so far in the search. Nodes which are not closer than this node are ignored.
With the patch, we keep track of a list of up to (currently) the 16 closest nodes visited so far. We then use the last node on the list as the threshold for deciding if we should visit somewhere -- unless the list isn't full yet, in which case we try anything. Either way, we ignore nodes if they're already on the list. There may be room to improve the implementation (reduce the number of sorts, keep a map to …
=> More reliable search

contrib/ansible/genkeys.go, src/yggdrasil/core.go
Fixes #671 sort-of. It should now catch the error when initializing the core and report something a little more useful, instead of crashing with a segfault when trying to start the switch. It should print an error along the lines of:
```
2020/03/31 18:16:48 Build name: yggdrasil-bugfix
2020/03/31 18:16:48 Build version: 0.3.13-0014
2020/03/31 18:16:48 Starting up...
2020/03/31 18:16:48 Failed to initialize core
2020/03/31 18:16:48 An error occurred during startup
panic: encoding/hex: invalid byte: U+006E 'n'
```
There's probably still room to improve that, but it's better than a segfault at least...
=> check if an error was returned by Core._init and return it if so

src/multicast/multicast_darwin.go
The issue was that `Multicast` was calling `Multicast.Interfaces()` instead of directly accessing `Multicast._interfaces`, and the former sends a message to itself and blocks until the message is handled, so it was deadlocking with itself.
=> maybe fix multicast deadlock on darwin

src/yggdrasil/link.go, src/yggdrasil/tcp.go
This is an experimental PR that allows pinning public keys in peering strings, e.g.
- pinning by signing public key: `tcp://host:port?ed25519=key`
- pinning by encryption public key: `tcp://host:port?curve25519=key`
- pinning by both: `tcp://host:port?ed25519=key&curve25519=key`
- pinning by multiple, in case of DNS round-robin or similar: `tcp://host:port?curve25519=key&curve25519=key&ed25519=key&ed25519=key`
The peering connection will fail if the remote side does not send us a matching public key, which helps to increase the guarantee that you are indeed peering with the node that you think you are peering with.
The extended peering URLs should be backward-compatible as older versions of Yggdrasil should just ignore the query strings.
It also juggles around things into `tcpOptions` and …
=> Public key pinning support

src/yggdrasil/dht.go, src/yggdrasil/link.go, src/yggdrasil/peer.go, src/yggdrasil/switch.go
EDIT: the other things I wanted to do here have been moved to #693, so I think the half of the changes that are here are OK on their own.
Updates to `future` to hopefully cover some edge cases where performance may have degraded compared to `develop`.
In particular: this should (hopefully) be faster about blocking and unblocking peers at the switch level, in cases where the TCP connection to a peer stops working. This still needs testing, so I'm not sure if it's done yet or not.
There's still work to do here, in particular I want to do something about switch queue sizes (currently they're hard coded, we should either read them from the config or find a reasonable way to make them zero configuration without hard coding a max size -- I think they mainly need to deal with bursts of traffic …
=> Misc updates for the future branch

src/yggdrasil/api.go, src/yggdrasil/core.go, src/yggdrasil/link.go, src/yggdrasil/packetqueue.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/simlink.go, src/yggdrasil/stream.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/tcp_linux.go, src/yggdrasil/tls.go
This is built on #692 and contains the other half of that PR.
The goal here is to remove the fixed maximum queue size and replace it with something that drops packets if (and only if) we appear to really be blocked.
The basic idea is:
1. There's no max size for each of the per-peer queues.
2. Instead, when the peer struct queues a packet, it sends a message to the link struct to see if it thinks we may be blocked.
3. The link struct responds if it thinks we are.
4. When the peer struct gets an affirmative response, it enters a "drop mode" where the queue size must be non-increasing. Every time the link send some packets, it reduces the max allowed queue size. When the link eventually becomes idle with an empty queue, it resets to normal mode. This ensures that a queue can grow as large as …
=> Update queue behavior

src/yggdrasil/dht.go
This reverts a recent(ish) change to the DHT, so we don't cache nodes that respond to DHT lookups unless they're legitimately important for our DHT.
I think the caching may be causing the DHT to become unbalanced, and cache information about unimportant nodes for too long (until they time out, since we won't bother pinging them if they're unimportant). So DHT lookups have more information to work with, but much of it is bad (due to e.g. coord changes). That's not useful, and leads to more DHT traffic (tending towards relatively few nodes), which I think may be causing some of the recent network instability.
=> Store less in the DHT

src/yggdrasil/peer.go
This should make dropping from the buffers less aggressive. The peer sends a message to itself to enter drop mode, instead of immediately beginning to drop packets. If an idle message sits on the queue between the original drop notification and the message that the peer sends to itself, then this will prevent the node from beginning to drop packets.
=> More buffer fine-tuning

src/yggdrasil/tcp.go
This checks if an TCP connection's local address is a ygg address or within a ygg subnet, and closes the connection immediately if it is.
This should prevent *some* cases of ygg-over-ygg tunneling. It does nothing against the general case of a VPN-over-ygg that then has ygg connections routed over it.
=> Ygg-over-ygg bugfix

src/yggdrasil/packetqueue.go
When testing #702 I see that a significant fraction of the remaining CPU time is spent on the packet queues, specifically the steps where queues are iterated over. We need something faster.
Temporarily, this PR replaces the queues with a single FIFO queue that head-drops when the peer struct decides that it has grown too large.
Ideally, we'll still want to keep separate queues per flow, it's mostly a matter of figuring out what pattern works. Historically, we've sent the packet from the queue that's using the least bandwidth, and dropped from queues randomly (with odds based on how much bandwidth the queue is trying to use). The problem with that is, the order of the queues changes as time passes, so we can't keep things sorted in advance. So we need to pick another criteria to decide …
=> Faster queue logic

src/yggdrasil/switch.go
Work-in-progress.
I noticed that, at least on my public node, a significant fraction of its time is spent iterating over the map in the current lookup table and doing a dist calculation to find the next hop (the map iteration is actually the more expensive part, it seems, but distance calculations aren't too far behind).
This tries to get rid of the iteration by producing a nested series of maps. Lookups happen by looping over coords and lookup up that coord in the next layer of the nested map, stopping when we either get to the end or run into a dead end in the nested map structure.
I'm not 100% sure this always reproduces exactly the same next-hop selection as the current code in cases where there are multiple valid next hops. If it doesn't, then it's at least not obvious why.
=> Precompute more for the switch lookup table

src/admin/admin.go, src/yggdrasil/api.go
Implemented Core.RemovePeer method
Changed AdminAPI call `removePeer`, now it's properly removing peers by `uri` and `interface` parameters.
Added a `disconnectPeer` AdminAPI call, which disconnects a peer by a switch port number.
=> Implement Core.RemovePeer method (#699)

src/defaults/defaults_freebsd.go
FreeBSD generally uses /usr/local/ for everything installed in userspace.
May want to put this on hold until we figure out how to solve the main problem with the FreeBSD port (not being able to destroy the interface on shutdown).
=> Set default conf file on FreeBSD to /usr/local/etc/yggdrasil.conf

src/multicast/multicast.go, src/yggdrasil/tcp.go
If the listener ever receives an error, then currently it will exit, and there's no mechanism to recover (other than maybe reconfiguring with a `SIGHUP`, I didn't test).
With this patch, instead of exiting when there's an error, check if the listener was stopped. If it wasn't stopped, then assume it's a temporary error, pause for 1 second (to avoid busy loops), and then continue trying to `Accept()` new connections.
Also, within the multicast code, currently we `panic` if we fail to get the list of network interfaces. Instead, return an empty map of interfaces/addresses if we failed to get them, as this can also be caused by temporary problems.
I'm not 100% happy with either of these changes, but they seem to (partially) work around a couple of issues reported in the chat. At the very …
=> Listener bugfix

src/defaults/defaults_openbsd.go
Specifying the full path to the interface in OpenBSD would result in:
panic: Interface name must be tun[0-9]*
Therefore, DefaultIfName should be changed to tun0 in order to make yggdrasil work out of the box.
=> Fix DefaultIfName for OpenBSD

contrib/apparmor/usr.bin.yggdrasil
The apparmor profile in it's current state won't allow resolving hostnames. We need `<abstractions/nameservice>` because we simply can't just allow `/etc/resolv.conf`. This is because systemd-resolved, resolvconf, and others rely on symbolic links to `/etc/resolv.conf` which would make this extremely complicated.  `<abstractions/nameservice>` deals with this complexity to allow every single one of those packages (systemd-resolved, resolvconf, ... ).
```
network inet stream,
network inet dgram,
network inet6 dgram,
network inet6 stream,
network netlink raw,
```
was removed because it's already included in `<abstractions/nameservice>`. Some permissions that are no longer needed in newer yggdrasil versions were also removed.
`owner /sys/kernel/mm/transparent_hugepage/hpage_pmd_size r,` was …
=> apparmor: allow yggdrasil to resolve hostnames

contrib/deb/generate.sh
The AppArmor profile in contrib forbids `/usr/bin/yggdrasil` from reading the file in `/var/backups/yggdrasil.conf...`. This works around that restriction by having the shell do the reading of `/var/backups/yggdrasil.conf...` file while providing the same exact functionality without making the AppArmor profile less restrictive. 
Another change is the safe perms for the `/etc/yggdrasil.conf` (so that config will have 0640 permissions). This is important because if we kept the default of 644 then any user (privileged or unprivileged) will have the ability to read the yggdrasil private key. We use a restrictive umask of 0027 to make this possible.
=> Fix AppArmor issue & have safe perms for config

src/yggdrasil/link.go, src/yggdrasil/tcp.go
This should fix a bug in link.go where having a peer that continues to make connection attempts would leak goroutines until the original connection is closed.
=> Fix goroutine leak in link.go

src/yggdrasil/dht.go, src/yggdrasil/packetqueue.go, src/yggdrasil/peer.go, src/yggdrasil/router.go, src/yggdrasil/session.go, src/yggdrasil/stream.go, src/yggdrasil/switch.go, src/yggdrasil/version.go, src/yggdrasil/wire.go
This patch builds on #741 by adding source routing to Yggdrasil. This is not meant for actual use, as certain aspects are incomplete and/or insecure (i.e. a node could lie by corrupting the source route, and there's nothing in the protocol that event attempts to detect this, nevermind fix or work around it, though in principle we could probably add something to do that if we decide to go with this approach).
This is mainly intended for performance studies, so we can compare how well source routing would do compared to hybrid routing or the current greedy routing scheme, using something like [meshnet-lab](https://github.com/mwarning/meshnet-lab) for example.
Some quick notes about how it works:
1. Any time traffic is forwarded through the network, the port number back to the previous hop …
=> Source routing (proof-of-concept)

src/address/address.go
This makes `src/address.AddrForKey` preallocate 128 bytes for `temp` before starting the address derivation. As [benches](https://git.tdem.in/tdemin/syg_go/src/commit/f5ca266cf10d01faf60a775f8a69e003f5bb5798/crypto_test.go#L35) versus the [version that already does that](https://git.tdem.in/tdemin/syg_go/src/commit/f5ca266cf10d01faf60a775f8a69e003f5bb5798/crypto.go#L31) in syg_go show, reallocating `temp` each time in the loop takes ~ 20% of the function runtime.
The change has no impact on function behaviour.
=> Preallocate memory when deriving address from key

cmd/yggdrasil/main.go, src/core/api.go, src/core/core.go, src/core/core_test.go, src/core/link.go, src/core/nodeinfo.go, src/core/proto.go, src/core/types.go, src/ipv6rwc/icmpv6.go, src/ipv6rwc/ipv6rwc.go, src/tuntap/iface.go, src/tuntap/tun.go
This patch has the `Core` export a `net.PacketConn` (specifically, it's an ironwood `PacketConn` with couple of functions wrapped to deal with the fact that sessions can carry either user traffic or protocol traffic).
The `ReadWriteCloser` logic is moved to a separate package (currently named `ipv6rwc`, but I'm not too strongly attached to that). The new package has the reusable IP-specific parts that `yggdrasil-extras` depends on (for mobile clients etc). The `Core` should be directly usable as a `PacketConn` for applications that want to use ygg as a generic transport (but otherwise reuse the existing network), with a couple of caveats:
1. if you don't keep calling `ReadFrom` in a loop, you won't respond to certain protocol traffic (nodeinfo, the `debug_remote*` functions, etc).
2. if …
=> Refactor PacketConn/ReadWriteCloser interfaces

cmd/yggdrasilctl/cmd_line_env.go, cmd/yggdrasilctl/cmd_line_env/cmd_line_env.go, cmd/yggdrasilctl/main.go
It's always recommended to split code into small units such as functions because this makes it more understandable. Many code linting tools ([RuboCop](https://rubocop.org) for Ruby programming language for example) have metrics which warn about too long functions: Assigment-Branch-Condition size, methods length, etc. Also this opens the opportunity of testing the code in future.
The previous PR (#814) have been accidentally closed by GitHub when I renamed the branch.
=> Split yggdrasilctl code into separate functions (refactoring)

src/core/link.go, src/core/tcp.go, src/core/tls.go
This PR does two things:
* Sets the TLS SNI on TLS peerings to the hostname in the peering URI (but *not* naked IP address literals)
* Allows overriding the SNI with a custom value by specifying the query string `?sni=...`
=> TLS Server Name Indication

src/address/address.go
This should fix #860. There might be a better fix for this, but apparently we overflow `key` and panic in some cases.
=> Fix panic in `address.GetKey()`

src/ipv6rwc/ipv6rwc.go
In the past we used to send back anything up to 900 bytes of the packet in the ICMPv6 Packet Too Big response, whereas now we seemingly only send back 40 bytes.
It turns out that sending back only the 40 bytes of IPv6 headers isn't enough for most operating systems to positively ID the flow to reduce the MTU. This PR updates it so that we can send up to 512 bytes instead (900 is probably excessive) — that should leave plenty of room for any number of IPv6 extension headers and the next protocol headers and some of the payload.
This seems to fix the problem in my testing.
=> Fix regression in Path MTU discovery

cmd/yggdrasil/main.go, contrib/mobile/mobile.go, go.mod, go.sum, src/core/api.go, src/core/core.go, src/core/core_test.go, src/core/link.go, src/core/options.go, src/core/tcp.go
This breaks the dependency on the Yggdrasil core needing to take a reference to a config struct. Instead, we pass in the options at startup as variadic parameters and Yggdrasil maintains the internal state itself in a protected fashion.
This means that unexpected mutations of the config struct from outside of Yggdrasil no longer create data races, and it means that we can now start an Yggdrasil node much more expressively, i.e. from `core_test.go`:
```
if nodeA, err = New(skA, ListenAddress("tcp://127.0.0.1:0"), IfName("none")); err != nil {
t.Fatal(err)
}
```
Responsibility for parsing the configuration JSON is now given to the `cmd/yggdrasil` itself.
=> Node setup refactoring

cmd/yggdrasil/main.go, src/admin/admin.go
It is useless to pass to method param to itself.
=> Refactor. Delete unused param

cmd/yggdrasil/main.go, cmd/yggdrasilctl/main.go, contrib/mobile/mobile.go, go.mod, go.sum, src/admin/getpeers.go, src/config/config.go, src/core/api.go, src/core/link.go, src/core/link_tcp.go, src/core/link_tls.go, src/core/link_unix.go, src/multicast/multicast.go, src/multicast/options.go
This allows setting priorities for multiple peerings *to the same node*, so that nodes that are multi-homed or have backup connectivity can be specifically configured to prefer certain links over others.
Note that it **does not prioritise peerings to different nodes** and deliberately does not provide the capability to prefer certain upstream nodes over others.
=> Priority support

src/core/link_tls.go
according to RFC5280 we can make tls certs never expire by setting their notAfter date to a value that is basically the end of time.
fixes #976
=> make tls certs never expire

contrib/mobile/mobile.go, src/core/api.go, src/core/core.go, src/core/link.go, src/core/link_socks.go, src/core/link_tcp.go, src/core/link_tls.go, src/core/link_unix.go, src/multicast/multicast.go
Right now if an outbound peering drops, it can take up to a minute to retry dialling. This speeds things up so that we attempt to redial after a single second in case the blip was transient, and we attempt it a couple more times to make sure.
=> Redial failed peering if possible

src/core/api.go, src/core/link.go
This uses a mutex instead of an actor for the link state as it is easier to reason about for now and changes a few other things.
=> Tweak link state locking, add comments, listener priority, other fixes

go.mod, go.sum, src/core/core.go, src/core/pool.go
This helps remove a few allocations from slices that no longer fit on the stack. It also pulls in an update to ironwood that reduces allocations in the `encrypted` package, and brings back @neilalexander's change that limited how fast keys can rotate.
All together, this increases iperf3 speeds between network namespaces on my machine from about 2.5 Gbps to about 3.5 Gbps. There's probably still more improvement to be gained (my old machine was getting >4 Gbps in v0.3.X), but it's a start.
=> Reduce allocations

src/core/api.go, src/core/link.go, src/multicast/multicast.go
This seems to fix the issue I was having where I was getting duplicate connections to the same peer, with only 1 of those connections being attached to a link struct (so we were leaking conns).
It removes the mutex and switches back to using an actor to manage the `links` object state. There's still more that could be done here to improve things. In particular, we could do something like get rid of the long lived goroutines and just periodically send a signal (with `time.AfterFunc`) to the `links` actor to retry the dead persistent links as needed (or fire up a new goroutine to call `add`, I guess), to avoid keeping idle goroutines around. Also fixes a race in the api where a non-atomic read was used to get the rx/tx bytes.
I noticed that, out of the box, fixing the link means my network …
=> Fix duplicate connections

src/core/link.go, src/core/version.go, src/core/version_test.go
The handshake format is already mostly extensible but including the total length of the data in the handshake lets us read the exact amount of bytes from the wire precisely. Previously both the sent and received handshakes had to be the same length.
=> Tweak link handshake

cmd/yggdrasil/main.go, src/multicast/advertisement.go, src/multicast/advertisement_test.go, src/multicast/multicast.go, src/multicast/options.go
This should make it easier for us to ignore nodes that we don't want to peer with automatically, either because they are a different node version to us altogether or because they don't have any configured TLS root CAs in common (for identifying closed networks).
=> Revise multicast format to include protocol version, discriminator for TLS roots

cmd/yggdrasil/main.go
It is expected a `syslog` implementation be it `rsyslog` or `journald` to have their own timestamping, so there's no point in duplicating that info.
=> cmd/yggdrasil: do not log timestamps to syslog

cmd/genkeys/main.go
This change is to display information about the key generation process.
Specifically, two bits of information are now displayed
* The number of threads created to search for keys, and
* The time taken to generate a successful "next best" key
=> Add output for threadcount and key generation time to cmd/genkey

contrib/mobile/mobile.go
The logger is created as local variable, but passed to multicast as `m.logger` :)
=> Fixes logger, adds some log messages.

src/core/options.go, src/core/options_test.go
=> Don't panic at startup when duplicate peers are configured

src/tun/tun_bsd.go, src/tun/tun_darwin.go, src/tun/tun_linux.go, src/tun/tun_other.go
Make the TUN setup failures more descriptive, otherwise the panic output is not very useful. Closes #1093.
=> Improve TUN setup logging

src/core/link.go, src/core/version.go, src/core/version_test.go
Right now, many handshake errors are not reported through the admin socket correctly, showing as `0s ago:` in `getPeers`. This should fix that.
=> Report errors during handshake stage

src/core/link.go, src/core/link_socks.go
Closes #1087. Allows connecting to a `tls://` peer over SOCKS, whereas the standard `socks://` scheme can only connect to `tcp://` peers.
=> Add `sockstls://`

src/core/link.go
It isn't clear to me why this would happen but let's guard the condition anyway.
=> Don't panic when connect returns `nil` (fixes #1086)

cmd/yggdrasil/main.go
Replaces #1088. This adds a command line `-publickey` switch that can be used in combination with `-useconf` or `-useconffile` in order to retrieve the public key. This can be used when the Yggdrasil process is not running, unlike the admin socket.
=> Add `-publickey` command line switch

src/core/link.go
This should ensure the backoff is correctly reset immediately after a successful handshake.
=> Tweak backoff success handling

src/core/link.go
This makes two changes to the link backoffs:
* The default maximum is now just over 1 hour, instead of 4.5 hours.
* A new peer option `?maxbackoff=` is added, minimum allowed value is `30s`, accepts minutes like `5m` or hours like `4h` etc. The backoff is exponential as normal up until that limit is reached, at which point the backoff is held at that limit.
Fixes #1117.
=> Adjust default backoff max to just over 1 hour, add `?maxbackoff=` peer option

CHANGELOG.md, README.md, contrib/msi/build-msi.sh
As of now, compiling in any golang versions older than 1.20 yields the following error:
```
../go/pkg/mod/github.com/quic-go/quic-go@v0.40.1/internal/qtls/go_oldversion.go:5:13: cannot use "The version of quic-go you're using can't be built using outdated Go versions. For more details, please see https://github.com/quic-go/quic-go/wiki/quic-go-and-Go-versions." (untyped string constant "The version of quic-go you're using can't be built using outdated Go...) as int value in variable declaration
note: module requires Go 1.20
```
=> [RFC] Bump minimum required go version to 1.20 in documentation as required by quic-go

cmd/yggdrasil/main.go, contrib/mobile/mobile.go, src/admin/getpeers.go, src/config/config.go, src/core/link.go
=> Minor Fixes

CHANGELOG.md
This PR includes the changelog for the v0.5.6 release.
=> Release: Yggdrasil v0.5.6

go.mod, go.sum, src/ipv6rwc/ipv6rwc.go, src/tun/iface.go, src/tun/tun.go, src/tun/tun_bsd.go, src/tun/tun_darwin.go, src/tun/tun_linux.go, src/tun/tun_other.go, src/tun/tun_windows.go
This PR updates the Wireguard dependency and updates to use new vectorised reads/writes, which should reduce the number of syscalls and improve performance.
This will only make a difference on Linux as this is the only platform for which the Wireguard TUN library supports vectorised reads/writes. For other platforms, single reads and writes will be performed as usual.
=> TUN vectorised reads/writes

src/tun/tun_windows.go
So, the function waiting for TUN to come up never succeeds:
```
func waitForTUNUp(ch <-chan wgtun.Event) bool {
t := time.After(time.Second * 5)
for {
select {
case ev := <-ch:
if ev == wgtun.EventUp {
return true
}
case <-t:
return false
}
}
}
```
I've tried the sleep for one second, and it works flawlessly on several PCs.
Another point - sometimes, if the service stop abruptly (in case of some errors) there is an old hidden device in the system, that we need to uninstall, and then create new.
=> Fixed wait for TUN to come up

go.mod, go.sum, src/multicast/multicast.go
This solution is bases on https://github.com/wlynxg/anet project. `github.com/wlynxg/anet` is a partial alternative implementation of the `golang.org/x/net` module. The goal of `anet` module is to provide workarounds of the issues https://github.com/golang/go/issues/40569 and https://github.com/golang/go/issues/68082 on Android 11+.
Tested on AOSP 13.
Resolves: #1149
=> Restore local peer discovery mechanism on Android 11+

.github/workflows/ci.yml, .golangci.yml, cmd/yggdrasilctl/main.go, contrib/mobile/mobile.go, go.mod, go.sum, src/admin/getpeers.go, src/core/api.go
This PR updates Ironwood to include the new RTT-based link costing and updates `yggdrasilctl` to report the cost in `getPeers`.
=> Link costing based on average RTT

cmd/yggdrasil/chuser_other.go, cmd/yggdrasil/chuser_unix.go, cmd/yggdrasil/main.go
different from https://github.com/yggdrasil-network/yggdrasil-go/pull/817 in that it can resolve user names, automatically use user's primary gid & allows specifying gid in the same argument, with `:` eg `username:groupname`.
feel free to criticize & suggest different argument name & description because i didn't put much of thought to that.
=> argument to change uid/gid

src/tun/tun_bsd.go
wireguard's CreateTUN() sets the MTU using the same ioctl(2), on both FreeBSD and OpenBSD.
Tested on OpenBSD (outputwith this patch):
```
2024/09/24 17:26:29 Interface name: tun0
2024/09/24 17:26:29 Interface IPv6: 201:26e:68f0:502e:f445:13eb:2fe1:f7cd/7
2024/09/24 17:26:29 Interface MTU: 16384
```
```
$ ifconfig tun0 | head -n1
tun0: flags=8051<UP,POINTOPOINT,RUNNING,MULTICAST> mtu 16384
```
```
53097 yggdrasil CALL  ioctl(10,SIOCGIFMTU,0xc0000376b8)
53097 yggdrasil RET   ioctl 0
53097 yggdrasil CALL  ioctl(10,SIOCSIFMTU,0xc0000376c0)
53097 yggdrasil RET   ioctl 0
53097 yggdrasil CALL  ioctl(10,SIOCGIFMTU,0xc0000377f8)
53097 yggdrasil RET   ioctl 0
53097 yggdrasil CALL  ioctl(10,_IOW('i',12,0x20),0xc00003777c)
53097 yggdrasil RET   ioctl -1 errno 25 Inappropriate ioctl for device …
```
=> tun: bsd: remove redundant ioctl to set MTU

contrib/mobile/build
The `github.com/wlynxg/anet` library depends on the `//go:linkname` linker feature [1]. However, since Go 1.23.0, the usage of `//go:linkname` has been restricted [2]. And now it's necessary to explicitly specify `-checklinkname=0` linker flag to use it.
[1] https://github.com/wlynxg/anet/blob/main/README.md#how-to-build-with-go-1230-or-later
[2] https://tip.golang.org/doc/go1.23#linker
Resolves: #1165
=> Fix Android build with Go 1.23.0 or later

src/tun/tun_freebsd.go, src/tun/tun_openbsd.go
This cleans up the mess to configure an IP address on a tun(4) device.
Handrolling a hardcoded ioctl(2) request is far from perfect, but Go (golang.org/sys/unix) is to blame here.
Tested on OpenBSD 7.6 -current where yggdrasil now drives the interface would use of ifconfig or other helpers.
=> Fix ioctl(2) code for OpenBSD

src/admin/admin.go
No need to extract it again when the url package provides it for us:
```
$ jq -n '{"AdminListen":"unix:///tmp/ygg.sock"}' | ./yggdrasil -useconf | grep 'admin socket'
2024/10/08 22:41:11 UNIX admin socket listening on /tmp/ygg.sock
```
Follow-up on #1176
=> Use UNIX socket patch from url struct

CHANGELOG.md
=> Yggdrasil 0.5.9

src/admin/admin.go
Creating UNIX sockets the listen() goroutine that races against the main
one dropping to an unprivileged user may cause startup failure when
privdrop happens before privileged filesystem access.
Setup or fail in New() and only do listen(2) in listen() to avoid this.
```
2024/11/03 21:15:27 Build name: yggdrasil-go
2024/11/03 21:15:27 Build version: 0.5.9
...
2024/11/03 21:15:27 Admin socket failed to listen: listen unix /var/run/yggdrasil.sock: bind: permission denied
```
Rerun, now the order is flipped:
```
2024/11/03 21:15:34 Build name: yggdrasil-go
2024/11/03 21:15:34 Build version: 0.5.9
[...]
2024/11/03 21:15:34 UNIX admin socket listening on /var/run/yggdrasil.sock
[...]
```
Fixes #927.
=> Create admin socket synchronously before privdrop

cmd/yggdrasil/chuser_unix.go
Changing the real and effective user/group IDs and the saved set-user/group-ID is not enough to get rid of intial access permissions.
The list of groups must be cleared also, otherwise a process changing from, e.g. `root:root` to `nobody:nobody` retains rights to access `:wheel` files (assuming `root` is a member of the `wheel` group).
For example:
```
uid=0(root) gid=0(wheel) groups=0(wheel), 2(kmem), 3(sys), 4(tty), 5(operator), 20(staff), 31(guest)
[1] 4337
COMMAND          USER     GROUP    SUPGRP
./yggdrasil -aut nobody   nobody   wheel,kmem,sys,tty,operator,staff,guest
```
Fix that so the process runs as mere
```
COMMAND          USER     GROUP    SUPGRP
./yggdrasil -aut nobody   nobody   nobody
```
Fixes #927.
=> Set groups when dropping privileges to not leak supplementary group access

cmd/yggdrasilctl/main.go, src/admin/admin.go, src/admin/getpeers.go, src/core/api.go, src/core/link.go
Updates `getPeers` to show how the data transfer rate per peer.
=> Expose download/upload rate per peer

CHANGELOG.md
=> Yggdrasil 0.5.10

cmd/yggdrasil/main.go
Straight forward thanks to all privileged operations being done early enough during startup.
=> Use pledge(2) on OpenBSD

contrib/openrc/yggdrasil
as it is long gone from the daemon code
and unexpectedly kills the daemon
=> contrib/openrc: remove SIGHUP logic
