src/yggdrasil/admin.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/router.go, src/yggdrasil/tun_darwin.go, yggdrasil.go
It's not great and still probably needs some work to include sessions and also to be thread-safe with the DHT, and also to properly label missing nodes, but it's a start.
Draw dot graphs: `echo "dot" | nc localhost 9001 | dot -Tpng -o test.png`
=> Some code to draw graphviz dot graphs of your view of the network

src/yggdrasil/tun.go, src/yggdrasil/tun_windows.go
This fixes the Windows problem.
=> Fix MTU issues with TAP adapters

misc/genkeys.go
This runs GOMAXPROCS numbers of goroutines instead of running in a single thread.
=> Multithread misc/genkeys.go

README.md, doc/Whitepaper.md
Documentation still needs a lot of work, but this at least removes any confusion about who is talking from the main readme and the whitepaper draft.
=> update doc to remove statements with a first person perspective

src/yggdrasil/tun_linux.go
When configuring the tun/tap device, instead of using `os/exec` to call `ip` commands, use [netlink](https://en.wikipedia.org/wiki/Netlink) instead.
This should allow users to `setcap()` the binary and then run as an unprivileged user. I'm told this works, but I haven't been able to do it successfully. Either way, netlink is still cleaner than launching external `ip` processes to configure.
=> Linux: use netlink instead of ip

src/yggdrasil/admin.go, src/yggdrasil/udp.go
Does 2 things:
1) Add a close packet to UDP. Looks like key packets, but with the second byte of the UDP header changed to a 1 instead of a 0. These should be sent automatically when a UDP peer disconnects (only during timeout, doesn't work if the program is killed right now).
2) Add a `removePeer` function to the admin socket. If called with a "udp:ip:port" peer info, it will send a UDP close packet, which should cause the remote end to instantly close their UDP connection (and respond with a UDP close packet, which will in turn close the connection on the local end).
The `removePeer` function currently doesn't work for TCP peers, as those links need a little work to make the TCPConn accessible to the outside, so the admin listener can close the connection. This isn't too hard to do, but …
=> UDP Close packet, admin removePeer

src/yggdrasil/router.go, src/yggdrasil/session.go
Fixes #66 (hopefully before it becomes a problem).
The previous behavior was to send a search (throttled to a max of once per second per session) when trying to use a session that hadn't responded in 6 seconds.
The new behavior is to send a ping (throttled to a max of once per second per session) when trying to use a session that hasn't responded in 6 seconds. If it remains unresponsive to pings for 6 seconds, then revert to the default behavior using searches.
This should cut down on some of the search traffic being forwarded through the DHT. Pings should normally be sufficient to keep a session alive. Searches should only happen if either the destination's coords change, if the node become unresponsive (e.g. goes offline), or if the session is idle for longer than the main session …
=> Try using session pings before searches for active sessions

src/yggdrasil/config/config.go, src/yggdrasil/config/i2p.go, src/yggdrasil/config/tor.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/dial.go, src/yggdrasil/tcp.go, yggdrasil.go
* add tor socks connectivity for onions
* refactor `tcp.go` to use `net.Conn`
=> Tor socks proxy support

.circleci/config.yml, contrib/deb/generate.sh, src/yggdrasil/admin.go, yggdrasilctl.go
The admin socket will now speak JSON, both in requests and in responses. This resolves #43.
In brief:
- The request verb should be given in the `"request"` field, along with any other fields required.
- Optional fields are reported in `"help"` with square brackets. Any field without square brackets is required for that verb.
- Optionally, the `"keepalive"` key can be set to `true` which will not terminate the admin socket connection after responding. This means the connection can be given multiple requests, which should be line-delimited.
- The response always contains the original request in the `"request"` field.
- The response body is always in the `"response"` field.
- Every response contains a `"status"` field, which is either `"success"` or `"error"`.
- An optional `"error"` field …
=> JSON support for admin socket

src/yggdrasil/core.go
Fixes a stupid bug in the last PR.
=> fix npe, these don't need to be pointers

yggdrasil.go
This squashes a nil pointer exception.
=> Set allowed encryption keys after start

src/yggdrasil/dht.go
This changes the type of dhtInfo.throttle to time.Duration (previously uint8 representing seconds). This is used to throttle the rate at which we ping a node in an attempt to fill any holes that appear in our DHT (important for bootstrapping).
Previously, the throttle started at 1 second, and increased by 1 second every time the node responded to a lookup, up to a maximum of 60 seconds. Now, it starts at 1 second, and it *doubles* every time we *send* a ping to the node *as part of DHT bucket maintenance*. This should avoid (some) unintended interactions with other DHT activities, like searches and the regular ~1/minute+ pings we send to check on nodes and discover nodes for new/closer buckets.
There's also some logic to skip the maintenance step for a bucket if we already know a valid …
=> Exponential DHT backoff

src/yggdrasil/peer.go
Fixes a bug I stumbled across when resuming from a suspend.
There's a race condition between `peers.removePeer(port)` (called by tcp.go when a peer disconnects) and `peers.sendSwitchMsgs` (called by the router when something updates or times out), where the former closes a channel just before the latter writes to it. This fixes it by recovering if the channel send panics due to the channel being closed, and updates the other instance of the channel send (at the start of linkLoop) just in case.
=> closed channel send bugfix

contrib/deb/generate.sh
Fixes a formatting error in the Debian package.
=> Fix debian control file

README.md
Update the readme to use the new address range.
=> address range changes

.circleci/config.yml
This collects the `yggdrasilctl` binary during CI builds for each platform.
=> Collect yggdrasilctl during CI builds

yggdrasil.go
So at some point recently, Windows 10 has now started converting things needlessly to UTF-16. This happens not only in PowerShell but even in Notepad!
Since Windows tends to prefix the conversion with a BOM, it's possible to detect easily, therefore the configuration is converted back down to UTF-8 before giving it to `hjson`. This prevents the panic at startup.
As a result, this pretty much fixes #119 in effect. 
Some extra code will need to be added for cases where the file might be UTF-16 but without a BOM, but I guess this is a lot less likely, and it removes the immediate issue for Windows users in the meantime.
=> Convert config from UTF-16 if a BOM is found

yggdrasil.go
Trivial cleanup that I forgot to do with this file in v0.2
=> clean up main yggdrasil.go imports and run gofmt

.circleci/config.yml, README.md, contrib/deb/generate.sh, contrib/macos/yggdrasil.plist, src/yggdrasil/address.go, src/yggdrasil/admin.go, src/yggdrasil/core.go, src/yggdrasil/debug.go, src/yggdrasil/dht.go, src/yggdrasil/icmpv6.go, src/yggdrasil/session.go, src/yggdrasil/switch.go, src/yggdrasil/tcp.go, src/yggdrasil/tun_darwin.go, yggdrasil.go
Pending review/merge of #129. Don't forget to squash merge! 🔨 
Changes:
- Address space change to `0200::/7` from `fd00::/8` (#122)
- UTF-16 conversion for configuration files (#129)
- Fixes to the Debian package control file (#124)
- Fixes to the launchd service file for macOS (#121)
- Fixes to the DHT and switch (#127)
=> Version 0.2.1

src/yggdrasil/tcp.go
This attempts to mitigate what I *think* was causing a difficult to reproduce bug when connecting over a lossy link.
What I think was happening was that nodes A and B connect. Node B times out due to a lost A->B keep alive packet, and immediately disconnects. The disconnect notification gets lost, so A doesn't immediately DC (keep alive traffic from B->A had gotten through fine, so A hasn't timed out yet).
Then B tries to start a new B->A connection. The key exchange goes through, and B tries to stay connected. A sees a duplicate connection and kills it, keeping the old / timedout connection that was closed from the B side earlier. Then A times out or finally gets the last of the old connection's stream including the EOF/close.
This patch adds a delay (equal to 1 tcp timeout, which is …
=> Mitigate connection cycling issue

contrib/config/yggdrasilconf.go
This is a small utility that makes configuration changes on the HJSON file.
It's not very robust, it isn't complete, but it is sufficient to do some testing with.
=> Add yggdrasilconf for testing with vyatta-yggdrasil

src/yggdrasil/admin.go, src/yggdrasil/defaults/defaults.go, src/yggdrasil/defaults/defaults_darwin.go, src/yggdrasil/defaults/defaults_linux.go, src/yggdrasil/defaults/defaults_other.go, src/yggdrasil/defaults/defaults_windows.go
=> Update admin socket error message and run gofmt

src/yggdrasil/admin.go, yggdrasilctl.go
This PR makes `yggdrasilctl` less case-sensitive, i.e. `getDHT`, `getdht` etc.
=> Make yggdrasilctl less case-sensitive

src/yggdrasil/tcp.go
according to documentation of io.Reader interface,
"Callers should always process the n > 0 bytes returned before considering the error err. Doing so correctly handles I/O errors that happen after reading some bytes and also both of the allowed EOF behaviors."
=> rearrange tcp reading loop

src/yggdrasil/session.go
Only split queues based on port number for TCP/UDP/SCTP and rely only on protocol number for other protos to prevent issues with IPIP, GRE etc which currently might be split into different queues based on length or other arbitrary values.
We also don't currently accommodate for the fact that the Next Header could be an IPv6 Extension Header, so that might also be desirable for us to check. Currently any IPv6 packet with an EH will be split into queues based on the first EH instead of the payload protocol.
=> Only split queues based on port number for TCP/UDP/SCTP

src/yggdrasil/session.go
The IPv6 Next Header attribute poses some challenges due to fragmentation and other conditions, so this PR effectively replaces #170 with the flow label instead.
The flow label seems to be reasonable enough to separate TCP sessions and reasonably related UDP/ICMP packets in my testing on macOS and Linux, and a little more loosely on Windows.
=> Use flow label instead of TCP/UDP/SCTP source/destination

src/yggdrasil/debug.go, src/yggdrasil/switch.go
Currently, when our parent changes root/coords, the switch resets the map of its latency relative to other peers. This patch extends this behavior, to reset *any* peer's latency map when it changes coords. This should help to mitigate some (hypothetical) issues, where nodes would switch to an effectively random parent if all peers update their coords at (roughly) the same time (e.g. all peers have a common ancestor, and that ancestor changed coord something). Now it *should* tend to cycle through them and return to the original parent if this happens, which is likely to still be the best in such a scenario.
It also makes some improvements to the sim links, so packet order is preserved, similar to if we were using TCP links.
=> More latency-based switch optimizations

.circleci/config.yml, contrib/semver/version.sh
This fixes some bugs I accidentally introduced in #228.
=> Fix circleci/semver bugs

src/yggdrasil/tun.go
This hopefully fixes #248, but I'm not sure how to test it...
=> Fix panic when writing to closed tun (from race during shutdown)

cmd/yggdrasilctl/main.go
This fixes some lazy parameter handling in `yggdrasilctl` which made it overly keen to crash.
=> Make yggdrasilctl less crashy

CHANGELOG.md
=> Update changelog for v0.3.2

build, src/yggdrasil/awdl.go, src/yggdrasil/mobile.go, src/yggdrasil/mobile_android.go, src/yggdrasil/mobile_ios.go, src/yggdrasil/multicast.go, src/yggdrasil/multicast_darwin.go, src/yggdrasil/tcp.go, src/yggdrasil/tcp_darwin.go, src/yggdrasil/tcp_other.go
This makes some minor changes in the name of mobile support, and also amazingly gets AWDL support to work on macOS. Hopefully it'll work for iOS too.
=> AWDL support, Android tweaks

src/yggdrasil/tcp.go
This fixes a bug in `tcp.go` where the source address in `InterfacePeers` or multicasting is restricted to selecting global unicast addresses and doesn't specify a source zone. This results in problems with, e.g. AWDL, where only a link-local address exists on the adapter. 
This PR will now select the first available global unicast address if available, or will select the last-resort address if not. In the case of an adapter having only a single link-local address then it will select that.
=> Fix source address selection when sintf specified

src/yggdrasil/tcp.go
This fixes source address selection when a source interface/zone is configured. This behaviour was broken probably by #311.
=> Fix source address selection

src/yggdrasil/awdl.go, src/yggdrasil/link.go, src/yggdrasil/mobile.go, src/yggdrasil/mobile_ios.go, src/yggdrasil/tcp.go
These are mostly just copies from the old code, adapted. I don't know if the positioning is exactly right for this stuff, hence why I've put it in a PR for review.
=> link.go: Connect/disconnect logging, check AllowedEncryptionKeys

contrib/busybox-init/S42yggdrasil
=> contrib/busybox-init: add init.d script for busybox init

contrib/docker/Dockerfile
Reverts yggdrasil-network/yggdrasil-go#333 after some issues were highlighted in the Matrix channel.
=> Revert "Simplifying Dockerfile"

src/yggdrasil/admin.go
This fixes #363 so that `getTunTap` will work properly again.
=> Fix getTunTap

contrib/openrc/yggdrasil
Here comes an init for OpenRC :)
=> contrib/openrc: add init file for OpenRC

cmd/yggdrasilctl/main.go
This fixes the `getRoutes` command in `yggdrasilctl`, closing #339.
=> Fix getRoutes 

src/yggdrasil/link.go, src/yggdrasil/switch.go
Fixes #355 (EDIT: and fixes #340) ...maybe.
=> Try to switch parents if a parent link is blocked

src/yggdrasil/switch.go
This seems to give more stable behavior in my tests.
=> use idle time in switch decisions to force it to try all links

contrib/deb/generate.sh
Not sure how far you want to take this, but adding this line was enough to build a functional Debian package
=> Add armel support to deb script

contrib/yggdrasil-brute-simple/.gitignore, contrib/yggdrasil-brute-simple/LICENSE, contrib/yggdrasil-brute-simple/Makefile, contrib/yggdrasil-brute-simple/README.md, contrib/yggdrasil-brute-simple/util.c, contrib/yggdrasil-brute-simple/yggdrasil-brute-multi-curve25519.c, contrib/yggdrasil-brute-simple/yggdrasil-brute-multi-ed25519.c, contrib/yggdrasil-brute-simple/yggdrasil-brute.h
I think the yggdrasil-brute-simple address generator is now mature.
https://github.com/fifteenthcommotion/yggdrasil-brute-simple
=> contribute decently fast yggdrasil address generator in C

src/tuntap/conn.go, src/yggdrasil/conn.go
Apparently I forgot to re-add ICMPv6 Packet Too Big messages in `modular` altogether. This adds a new `ConnError` condition for packets that are too large, and the TUN/TAP module now handles this condition correctly.
=> Re-add ICMPv6 packet too big handling

src/yggdrasil/conn.go
Conn.Read was returning an error when a packet failed to decrypt (corrupted) or was dropped due to having a bad nonce (duplicate or very old). Instead, just drop the packet and keep trying to read until we have something useful or a timeout.
=> Conn.Read don't return useless errors

src/yggdrasil/conn.go
Fixes a concurrent map read by moving the initial search check and creation/start (if it doesn't already exist) into the router goroutine.
=> Bugfix in dial code

src/yggdrasil/conn.go, src/yggdrasil/dialer.go, src/yggdrasil/router.go, src/yggdrasil/session.go
fix nil pointer deref if searches fail, block dial until a search succeeds or a timeout passes (todo: replace timer with context)
=> Dial fixes

src/yggdrasil/conn.go, src/yggdrasil/session.go
fix channel multiple close bug and concurrency bug in the way sessionInfo.close was being called
=> more bugfixes

src/yggdrasil/conn.go
fix another panic from a send on a closed session worker channel, from races between Conn.Read/Write/Close
=> Another Conn bugfix

src/tuntap/ckr.go, src/tuntap/icmpv6.go, src/tuntap/iface.go, src/tuntap/tun.go, src/tuntap/tun_windows.go
This should fix TAP mode, which @Arceliar mentioned was affecting Linux in the latest `develop` builds and should also fix #454.
=> Fix TAP mode

src/admin/admin.go
This contains a couple of minor fixes to the admin socket:
- Return a more useful error when the client requests a command that doesn't exist (fixes #385)
- Reduce the logging level of admin socket recovers to `debug` instead of `error`
=> Handle admin socket error cases better

src/tuntap/conn.go
Right now there seems to be a problem with conn readers not cleaning up properly in the TUN/TAP module. This PR changes things a bit so that we no longer call a new goroutine for every read—instead we open one per conn—and that goroutine correctly times out along with the conn itself.
I'm hoping this will fix some goroutine/memory leakage that I've been seeing in the `develop` branch.
=> Try to fix TUN/TAP conn reader leakage

src/yggdrasil/conn.go
The function looks like `Read([]byte) (int, error)`. If the argument slice is passed directly to the crypto worker, and then we cancel due to timeout while the crypto worker is running, it means the crypto worker can still mutate the slide even after `Read` returns. This moves the logic that updates the argument slice out of the crypto worker and into the main part of the function that gets executed by the caller.
=> fix possible unsafe memory use in Conn.Read

src/tuntap/conn.go
In `develop` we were sending all `yggdrasil.Conn`-related errors to the logger error channel, even though some errors like session closures are benign. The log would therefore end up with quite a few entries like this which look bad but are actually expected:
```
2019/07/21 08:13:15 conn=0xc0003e6af0 TUN/TAP conn read error: session closed
```
This PR directs session closure errors to the logger debug channel instead. Other connection-related errors will continue to be sent to the logger error channel.
=> Redirect Conn session closure errors to debug channel

src/admin/admin.go
=> Don't send IP back twice with getPeers

src/yggdrasil/session.go
Without this change, if 1 session is flooded, then drops happen in a general buffer in the switch that carries *all* traffic to the self node.
With this change, traffic is quickly delivered by the router to a per-session buffer. If the per-session buffer becomes flooded, that one session will start to drop packets, but it won't block or force drops on other sessions.
=> Per-session front-dropping buffers for incoming traffic

src/yggdrasil/conn.go
Since the tun/tap code uses `yggdrasil.Conn` objects without setting deadline, I modified the way `Read` and `Write` are implemented to avoid allocating a `util.Cancellation` in cases where no deadline is set.
This speeds things up a bit regardless of MTU, but is (proportionally) more significant for small MTU:
mtu=1280: 480 Mbps -> 550 Mbps
mtu=65535: 4.3 Gbps -> 4.5 Gbps
=> More speedup

src/yggdrasil/conn.go
Fixes #533 (hopefully).
Previously, the callback at the end of a search would set up a session and then immediately return it, before having set the `sessionInfo.conn` field, and then another thread would set that field. During that time, if the other end happened to send anything to the session (particularly a ping and then some traffic), then this update could cause a race leading to a `nil` pointer dereference.
Now, if the search succeeds and creates a session, the callback sets `sessionInfo.conn` to the associated `*yggdrasil.Conn` immediately, before the router has a chance to finish the current behavior and start passing any packets to the session. At least, I think that's what would happen currently. We need to be careful about how we update this if/when we ever make something …
=> Fix race between router and dial code

src/multicast/multicast.go
Yggdrasil has always sent out multicast beacons every 15 seconds when enabled. This PR is a simple change to start that interval at 1s, and then add another 1s with each beacon until the interval reaches 15s.
This may help Yggdrasil to peer faster in some cases where Yggdrasil is brought up during system boot but some network interfaces may not be configured yet.
=> Gradually increase multicast interval from startup

CHANGELOG.md
This includes changelog updates for v0.3.9 and a minor tweak to the layout for v0.3.8.
=> Changelog for v0.3.9

CHANGELOG.md, contrib/systemd/yggdrasil.service, go.mod, go.sum, src/tuntap/conn.go, src/yggdrasil/conn.go, src/yggdrasil/core_test.go, src/yggdrasil/tcp_linux.go, src/yggdrasil/tcp_other.go
Pending release on Thursday.
@Arceliar — if you don't mind updating the changelog that'll be great.
=> Version 0.3.10

src/multicast/multicast.go
This removes the atomic `isOpen` from the multicast module and ensures that `isOpen` is only accessed by the multicast actor.
=> No longer use atomic for isOpen in multicast

go.mod, go.sum
This is mostly to fix some missing `go.mod` and `go.sum` lines that were appearing if building on linux.
=> update a few deps and run 'go mod tidy'

CHANGELOG.md
This contains a proposed changelog for v0.3.11.
=> Changelog for v0.3.11

cmd/yggdrasil/main.go
This adds `-address` and `-subnet` command line arguments to `cmd/yggdrasil/main.go` which allow you to quickly get the IP address and/or subnet from your Yggdrasil config. This is a commonly requested feature.
Example usage:
```
./yggdrasil -useconffile /etc/yggdrasil.conf -address
201:6243:84d5:813a:2a98:e6a:4279:318
```
```
./yggdrasil -useconffile /etc/yggdrasil.conf -subnet
301:6243:84d5:813a::/64
```
=> Add -address and -subnet command line options to cmd/yggdrasil

cmd/yggdrasil/main.go
`Loglevel` seems better than enumerate each log level
=> Use loglevel instead comma-separated list of logging

src/tuntap/tun.go, src/yggdrasil/conn.go, src/yggdrasil/search.go
Reduce search traffic and add some search logging at the debug level.
Also, gofmt sorted a few includes.
=> Search updates

src/yggdrasil/switch.go
After reports of a possible memory leak, I tried stress testing two instances of ygg between network namespaces, and saw that I was able to (sometimes, randomly but fairly frequently) reproduce the problem. In other cases, packet loss increased dramatically, packets started being reordered, and bandwidth in iperf3 tests generally dropped by ~2 orders of magnitude.
The only major change to the path of packet flow in the last release cycle was switching to wireguard for the tun driver, but reverting to the old water code did not seem to affect the problem. The only other place where things changed (and where I can see how a memory leak could happen) is if a bugfix to windows packet reordering issues somehow caused packets to remain buffered in the switch indefinitely. Modifying that fix …
=> Fix memory leak

contrib/ansible/genkeys.go
I never generated any "good" keys, because I couldn't be bothered to have a process running on a terminal with no indication of progress for a long time. Now this isn't a problem anymore ^^
=> add a progress bar to the ansible key generator

src/multicast/multicast.go, src/multicast/multicast_darwin.go, src/multicast/multicast_other.go, src/multicast/multicast_unix.go, src/multicast/multicast_windows.go
This PR aims to refactor the multicast code so that it makes less syscalls and therefore doesn't sip so much CPU on embedded systems.
=> Refactor the multicast code a bit

README.md
See [here](https://github.com/NixOS/nixpkgs/blob/master/pkgs/tools/networking/yggdrasil/default.nix).
=> README: mention Nix package

src/yggdrasil/link.go, src/yggdrasil/switch.go
This is my attempt at fixing #710 if I'm right about the cause of the problem. I haven't managed to reproduce the problem yet, so I don't know if this is even the right direction to go.
I think there's a race between when we remove a peer and when we block an existing peer in the switch. If that's true, then I think the problem was caused by a peer being removed, a new peer being added, and then a timeout message for the old peer being handled by the switch. This would put the switch into a state where the peer is blocked, and the link into a state where it doesn't know that the peer is blocked (so it never sends a message to the switch to try to unblock it).
If I'm right about that, then this *maybe* fixes it without spamming the switch with messages about every packet sent or received. …
=> [future] possibly fix missing switch peer issue

CHANGELOG.md
Draft changelog, I think I got most of the changes, but feel free to add/edit
=> Update changelog for v0.3.16 release

src/tuntap/tun.go
We have to check tun.config is not nil before first use, not after.
=> Check tun.config is not equal to nil before usage

src/admin/admin.go, src/core/api.go, src/core/proto.go
* Added type alias `core.AddHandlerFunc`
* Renamed attributes of `core.protohandler`
=> Really tiny refactoring of "src/core"

src/core/debug.go, src/core/tcp_darwin.go, src/core/tcp_linux.go, src/core/tcp_other.go, src/defaults/defaults_darwin.go, src/defaults/defaults_freebsd.go, src/defaults/defaults_linux.go, src/defaults/defaults_openbsd.go, src/defaults/defaults_other.go, src/defaults/defaults_windows.go, src/ipv6rwc/ipv6rwc.go, src/multicast/multicast_darwin.go, src/multicast/multicast_other.go, src/multicast/multicast_unix.go, src/multicast/multicast_windows.go, src/tuntap/tun_bsd.go, src/tuntap/tun_darwin.go, src/tuntap/tun_linux.go, src/tuntap/tun_other.go, src/tuntap/tun_windows.go
I believe this should fix #840.
=> Fix incorrect mutex use in ipv6rwc

src/core/link.go
This error message was shown for incoming connections which is made clearer with the changed message
and after a chat with neilalexander he suggested to downgrade it to debug as it doesn't make sense to litter the log with them.
=> Make message clearer and downgrade

CHANGELOG.md
We'll want to fix the date when we actually release.
=> Version 0.4.3 changelog

cmd/yggdrasilctl/main.go
Very simple fix, subj self-explainable.
=> Fix printing self coordinates in getself command of yggdrasilctl

contrib/mobile/mobile.go
Closes yggdrasil-network/yggdrasil-android#14
=> Fix Android multicast crash

src/core/link.go
This uses a 6 second deadline for timeouts instead of using `util.FuncTimeout` at 30 seconds for the read and then again for the write.
If the handshake doesn't complete within 6 seconds then it's going to probably collapse when we give the connection to Ironwood and it tries to do a keepalive anyway.
=> Use deadline for link handshake

src/admin/addpeer.go, src/admin/admin.go, src/admin/removepeer.go, src/core/api.go, src/core/core.go, src/core/link.go, src/core/options.go
=> Reimplement AddPeer and RemovePeer for admin socket

contrib/mobile/mobile.go
In order to implement https://github.com/yggdrasil-network/yggdrasil-android/issues/25 we need these new methods.
=> Added two new methods to `mobile` package

CHANGELOG.md
Planning to release on Saturday.
=> Version 0.4.7

src/core/link_tcp.go, src/core/link_tls.go
=> Try all addresses when connecting to a DNS name

src/tun/tun.go
This means that we no longer need to fork `tun` to swap out RWCs.
=> Define interface for RWCs

cmd/yggdrasilctl/main.go, go.mod, go.sum, src/admin/getpeers.go, src/core/api.go
This adds RTT measurements from the sig reqs into `getPeers`.
=> Measure RTT, report in `getPeers`

go.mod, go.sum, src/core/link.go, src/core/link_ws.go, src/core/link_wss.go
ws:// can be listened and dialed
wss:// is a convenience link for ws:// that supports dialing to ws:// peer.
=> Implement websocket (ws:// and wss://) links

cmd/yggdrasil/main.go
This fix fixes two issues: https://github.com/yggdrasil-network/yggdrasil-go/issues/993 & https://github.com/yggdrasil-network/yggdrasil-go/issues/1098
=> Fixed Windows service life-cycle.

src/admin/admin.go
This stood out to me while reading the code:  [7:] is skipping "unix://", so why not do that?
Doing so reveals a bug in the last line changed, where chmod(2) failure would print just the prefix, not everything but it... easy to miss, but now this kind of bug can no longer happen.
=> Replace repeated subscripts with single TrimPrefix
